### ISSUE TITLE
Contribute Zenodo crawler to DataLad

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#104]
## Purpose

When the Zenodo crawler is functional and tested, contribute it back as a crawler to DataLad so that others can use it. 

@joeyzhou98 @mih

**Comment by mih** [comment]
I am thinking of implementing something along the lines of https://github.com/datalad/datalad-osf for ZENODO. Ideally, it could be based on the code you already have. But I have difficulties finding it. Can you point me to it please? Thx!

**Comment by cmadjar** [comment]
Hi Michael,

I am not sure if this is what you are looking for but our Zenodo specific Crawler code can be found here: https://github.com/CONP-PCNO/conp-dataset/blob/master/scripts/Crawlers/ZenodoCrawler.py

Our conp-dataset crawler is https://github.com/CONP-PCNO/conp-dataset/blob/master/scripts/crawl.py, which uses the libraries in https://github.com/CONP-PCNO/conp-dataset/tree/master/scripts/Crawlers to crawl OSF or Zenodo.

Hope this helps :-)

**Comment by cmadjar** [comment]
@PapillonMcGill can you discuss this with Tristan and identify what needs to be done for that issue?

**Comment by mih** [comment]
Thanks for the pointers. From my POV this can be closed, and the code looks fine. Given the MIT license, I am planning to incorporate this code into a future datalad-zenodo extension, which will feature a range of commands, including the export of a datalad dataset from a zenodo record, but also the deposition of a cloneable datalad dataset at zenodo.
