### ISSUE TITLE
Missing logos for datasets

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-dataset#116]
## Purpose
I have added a default icon for the datasets in the /search page but having a specific logo for each datasets would be nice.

Some dataset logos can be found in `https://github.com/CONP-PCNO/conp-portal/tree/master/app/static/img`

## Context
Because maintaining those logo is a per dataset task

## Possible Implementation (optional)
Have a logo.png in the root directory of each dataset
or 
Have a logo property in the DATS file which is the url to the logo

**Comment by glatard** [comment]
I think both your solutions should be available: look for a logo URL in DATS.json, fall back on logo.png at the root if not found.

**Comment by cmadjar** [comment]
@glatard @xlecours Should this issue be closed? I feel like this one was completed (I see logos next to the datasets) but maybe I am wrong.

**Comment by glatard** [comment]
The only remaining issue regarding that is that some datasets, in particular the ones crawled from Zenodo, have their logos specified as URLs and the portal doesn't display them. I guess that's one for @liamocn
