### ISSUE TITLE
PREVENT-AD description typo 

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-dataset#126]
Please update to `Alzheimer’s Disease` instead of `Alzheimer Disease` and `Alzheimers Disease`

**Comment by emmetaobrien** [comment]
I have just corrected those and published to my fork, so that will be corrected when https://github.com/CONP-PCNO/conp-dataset/pull/125 is accepted.

**Comment by xlecours** [comment]
Resolved in #125
