### ISSUE TITLE
Pipelines creation date

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-dataset#129]
To feed the conp-portal dashboard, we would need the creation date of the pipelines.
Looking at the zenodo_crawler I noticed that a `GET https://zenodo.org/api/records/?type=dataset&q=keywords:%22canadian-open-neuroscience-platform%22` returns an object in which the hits contains a "created" property. Could it be add to the descriptor file?

**Comment by glatard** [comment]
@joeyzhou98, could you have a look at that? We need to get the upload date of pipelines, not datasets. I think it might take an update on bosh search.

**Comment by glatard** [comment]
Duplicate of https://github.com/CONP-PCNO/conp-portal/issues/248
