### ISSUE TITLE
[Dataset] Make Simon's Dataset Splitable

### ISSUE THREAD

**Issue by kchatpar** [CONP-PCNO/conp-dataset#15]
Simon's data set can be found [here](http://fcon_1000.projects.nitrc.org/indi/retro/SIMON.html). Simon's dataset can be found under the Simon_Dataset branch. Dataset needs to be split into two independent datasets one public and one private. There needs to be a symlink connecting the two datasets.

**Comment by glatard** [comment]
Hi @kchatpar, path in the DataLad dataset aren't dependent on whether the data is public or private. It's up to the storage platform to enforce access rights.
