### ISSUE TITLE
Continuous integration of datasets

### ISSUE THREAD

**Issue by paiva** [CONP-PCNO/conp-dataset#16]
* We need to create a document outlining how to test PRs and to decide what is a good dataset to merge on `conp-dataset`

* It would be nice to build some automation around this, maybe look into Travis to see if we can automate some of the tests (like valid links)

* Also, we will require 2 reviewers before merging a PR

**Comment by paiva** [comment]
Should this be a document inside this repository or part of `conp-documentation`?

**Comment by glatard** [comment]
I think it should be a markdown file in this repo and a `.travis.yml` file.

**Comment by jbpoline** [comment]
I'll create something on the doc

**Comment by glatard** [comment]
Sorry @jbpoline, I really think these requirements should be in conp-dataset as it is very specific to this repo and might evolve with it.

**Comment by glatard** [comment]
We should also consider creating a `develop` branch for the dataset and have release cycles.

**Comment by glatard** [comment]
Can we list here the requirements before a PR can be merged, before we add them to Travis tests? 
[ ] dataset can be installed, recursively if it has sub-datasets
[ ] every file in the dataset has a URL
[ ] every file can be retrieved *or* requires authentication (not sure how to test when authentication is required)
[ ] DATs model is present and valid

**Comment by jbpoline** [comment]
Shouldn't we also testing that when logged on the portal we can actually download the data ? Not sure that can be automated but we shouldn't have hundreds of datasets soon, so to start with this could be manual.

**Comment by glatard** [comment]
Here is a summary of TODOs regarding this:
- Create a .travis.yml file and add the project to Travis. Add Travis badge to README.md
- Using Datalad's Python API, create a test script that iterates through the sub-datasets and checks that:
    * Dataset can be installed, recursively if it has sub-datasets
    * Every file in the dataset has a URL
    * Every file can be retrieved or requires authentication (not sure how to test when authentication is required)
    * DATs model is present and valid
    * If dataset is derived data, raw data is a sub-dataset
- Add a PR template containing this checklist.

Notes:
* It might be too heavy to test "every file in the dataset" in every test build. I guess a random sub-sample of, say, 20 files max should be fine.
* [Boutiques](https://github.com/boutiques) contains an example of .travis.yml and PR template (in dev branch).
* @jbpoline testing that the datasets can be downloaded from the portal should be tested in the portal repo, not here. Here we should only make sure that the DataLad repo is clean and working.
* Once this is merged, we should also configure the repo to require 2 reviews before merging, and forbid directs pushes without PRs.

@joeyzhou98, that's your next task when https://github.com/CONP-PCNO/conp-portal/pull/55 is merged. You may want to split this in two PRs: (1) basic integration with Travis, no DataLad stuff, (2) DataLad tests. You will have to get up to speed with [DataLad](https://www.datalad.org): it will take some sweat but hopefully you will find it cool eventually!

**Comment by glatard** [comment]
A few questions showed up as @joeyzhou98 is working on this:

1. Some datasets, for instance the OpenNeuro ones, require configuration for DataLad to be able to get data. For instance: `git annex enableremote <blah>`.

-> We suggest to require that such configurations are put in a `config.sh` file at the root of the dataset. `config.sh` would be sourced by the testing framework before attempting to get data. @joeyzhou98, that means that `config.sh` files might also be in sub-datasets: you should find them, cd to their directory, and run them recursively in the dataset. 

2. From early tests, a few datasets seem to be broken. We have two options:
a. Leave them in the repository. This will make tests break and pollute tests output for the coming PRs.
b. Remove them from the repository, create an issue to fix them.
I'd prefer option b. 

Please let us know what you think @paiva, @jbpoline.

**Comment by glatard** [comment]
Notes from the dev meeting today:
1. We agreed on having a `config.sh` at the root of the datasets for configuration. If it exists, this script should be sourced.
2. We will go with option a.: leave the datasets in the repo and test them.

Additional comments:
* We will also request that the dataset has a `README.md` file at the root of the dataset.
* The DATS file must be called `dats.json` and be stored at the root of the dataset.
* DATS validation should be left aside for now: @PapillonMcGill will write a validator and add it to the tests.

**Comment by glatard** [comment]
This is addressed in #55.

**Comment by gi114** [comment]
Hi,

Thank you for sharing the information.

I am currently writing the dats validator and will definitely share what I
have for the moment this is the link:
https://github.com/CONP-PCNO/dats-validator

Unfortunately I am in on Thursday and Friday every week only, so apologies
for missing other meetings. I will try to catch up as much as possible, so
feel free to send me any relevant things discussed.

As a plan with JB, the dats validator should validate dats.json files based
on required, recommended and optional fields. It will output an error and a
notification of the missing fields if any required field is not present,
while it will output a warning and a notification of the missing fields if
any recommended field is not present.

Such semantic validation will be paired with structural validation of the
json file provided by the JSON library.

The full validation will be added to the datasets tests currently being
implemented, once they will be approved.

So let me know what you think,

Best
Giulia

Il giorno mer 31 lug 2019 alle ore 10:28 Tristan Glatard <
notifications@github.com> ha scritto:
