### ISSUE TITLE
Regeneration of phantom, preventAD data links for more stable servers

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#165]
The multicenter-phantom and preventAD-open datasets currently link to file archives stored on development machines (phantom-dev.loris.ca and conp-dev.loris.ca respectively.)  While these sites are currently functional, they may not remain so longer term, and it will be beneficial to regenerate datalad archives pointing at more stable addresses (e.g. phantom.loris.ca).

**Comment by emmetaobrien** [comment]
I have now got a LORIS crawler working and crawling phantom.loris.ca/api/v0.0.3-dev/projects/loris/images is under way.

**Comment by emmetaobrien** [comment]
This crawl is complete and looks like it worked.

**Comment by emmetaobrien** [comment]
I have now set up to crawl PreventAD data once that dataset is reorganised.  As of now, the PreventAD dataset consists of ~21,000 files in a single directory, and a version of this dataset with BIDS file and directory structure is due soon.

**Comment by cmadjar** [comment]
@emmetaobrien should this issue be closed since you moved the card to done?

**Comment by emmetaobrien** [comment]
Yes, it should.
