### ISSUE TITLE
Write a script to automatically convert datasets to a datalad dataset

### ISSUE THREAD

**Issue by kchatpar** [CONP-PCNO/conp-dataset#22]
Write a script that traverses the directory of a dataset and executes the commands in each respective directory to convert the file structure to a Datalad dataset.

**Comment by gi114** [comment]
Hi,

We have documented procedures for adding a dataset to datalad: 
https://github.com/CONP-PCNO/conp-documentation/blob/master/datalad_dataset_addition_procedure.md

I would suggest to close to issue of @jbpoline agrees

**Comment by glatard** [comment]
@jbpoline and @kchatpar, do you think that another integration procedure than what is described in https://github.com/CONP-PCNO/conp-documentation/blob/master/datalad_dataset_addition_procedure.md would be useful?

**Comment by glatard** [comment]
Closing this, feel free to reopen if the above-mentioned documentation doesn't address it.
