### ISSUE TITLE
Cannot PUBLISH new dataset to CONP

### ISSUE THREAD

**Issue by gi114** [CONP-PCNO/conp-dataset#223]
I was adding the current [dataset](https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/QAIMTK) to this repository (CONP/conp-dataset) and I encountered an issue at the very end of the process when trying to publish the change. I have been following this [guide](https://github.com/CONP-PCNO/conp-documentation/blob/update_of_datalad_dataset_addition_doc/datalad_dataset_addition_experimental.md). The process is really smooth as file sizes in the dataset are small (max 1Mb) and can very well be stored in github. So, what I do is the following

1) I make sure the CONP/conp-dataset is up to date, make a branch to work on
2) I create the new-dataset repo in CONP/conp-dataset/projects
3) I create the sibling and edit the .gitmodule accordingly
4) I add the /project/new-dataset files to datalad with ``datalad add --to-git *``(successful)
5) I run ``datalad save`` and ``datalad publish`` to the _sibling repository and it works fine_
6) I run ``datalad save`` and ``datalad publish`` to CONP/conp-dataset _origin_  with ``datalad publish --to origin`` and I get the following error:

```
[ERROR  ] failed to push to origin: git-annex -> origin/git-annex [remote rejected] (failed); Reusing-Neuro-Data -> origin/Reusing-Neuro-Data [remote rejected] (failed); [publish(/home/giuly/Documents/NeuroHub/conp-dataset)] 
publish(error): . (dataset) [failed to push to origin: git-annex -> origin/git-annex [remote rejected] (failed); Reusing-Neuro-Data -> origin/Reusing-Neuro-Data [remote rejected] (failed);]
```

Where ``Reusing-Neuro-Data`` is the name of the branch I am working on

I tried this multiple times to be sure nothing went wrong. I am not sure of the reason. I tested I do have push access to CONP/conp-dataset, so that is not a problem.

There might be some problem with the submodule as I get this error when simply trying ``git push -f``
```
remote: error: object 3e34d03b8b8533638926d9709a777d5ae3bae9e6: gitmodulesSymlink: .gitmodules is a symbolic link
remote: fatal: fsck error in packed object
error: remote unpack failed: index-pack abnormal exit
```
Let me know if you have any ideas...

Thanks

**Comment by glatard** [comment]
Hi @gi114, nice to see data from FRDR coming!
1. Is your submodule available somewhere on GitHub? It should be.
2. You surely don't have push access to CONP/conp-dataset. If not done already, you should fork the dataset, push to your fork, and then PR to CONP/conp-dataset.
3. Even though the data files are small, they should be annexed. We don't want any data in the dataset repo.

**Comment by gi114** [comment]
Hi @glatard, thank you for your message. So I did try working from my fork as well (sorry I did not mention that), and got same result. I upgraded to datalad 0.12.2 now, so maybe that could have been the problem?

@emmetaobrien got it working in the meantime. 

I am not sure which special remote we should use for this dataset, so I will update the repo accordingly. The [dataset page](https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/QAIMTK) has a zip file link, and one possibility is to add that url to git annex (thus using a web special remote), which may not preserve the dataset structure though. If that is not a problem, we can use the web special remote

**Comment by glatard** [comment]
the web remote sounds good, but if the data is in a single zip file we should use datalad's archive mode so that the individual files in the archive are exposed in the dataset.

**Comment by gi114** [comment]
Yes, sounds good to me

**Comment by glatard** [comment]
Hi @gi114, is this still an issue?

**Comment by emmetaobrien** [comment]
I was not able to duplicate the behaviour @gi114 was seeing; the Reusing-Neuro-Data dataset is now correctly loaded into the portal, but we have not actively identified or fixed whatever the underlying problem was here.

**Comment by glatard** [comment]
ok, so closing this, feel free of reopen if needed, @gi114

**Comment by gi114** [comment]
Hi @glatard,
I just tried publishing a different dataset, from FRDR still. I get the same behavior when trying to publish to origin

```[ERROR  ] failed to push to origin: git-annex -> origin/git-annex [remote rejected] (failed); FRDR-multimodal-2 -> origin/FRDR-multimodal-2 [remote rejected] (failed); [publish(/home/giuly/Documents/NeuroHub/my-conp-dataset/conp-dataset)] 
publish(error): . (dataset) [failed to push to origin: git-annex -> origin/git-annex [remote rejected] (failed); FRDR-multimodal-2 -> origin/FRDR-multimodal-2 [remote rejected] (failed);]
```
I am working on my fork of conp-dataset, updated with last changes. I am really not sure why. Do you have any ideas?

**Comment by glatard** [comment]
@gi114 can you send the full output of the following command?
```
git remote -v # (executed from the dataset directory)
```

**Comment by emmetaobrien** [comment]
Problem identified and solved, working with @gi114 just now.

Since the recent update to v12.n DataLad has been more consistent about annexing everything unless specifically instructed not to, and every time one edits and saves a file it will be annexed unless `datalad add --to-git <filename>` is used again.

The particular failure mode we were seeing here is due to DataLad annexing the .gitmodules configuration file after it is edited, and then not being able to identify submodules.

**Comment by gi114** [comment]
Yes, that's right, it is clear now

**Comment by zxenia** [comment]
I had the same issue today, I will leave a comment here if someone else will encounter it in the future:
what worked for me - I did edit `.gitmodules` file after I saved and published a new project dataset


from `projects/<newprojectname>`:
```
datalad save
datalad publish --to github
```

then:

```
cd ../..		(this should put you in ~/conp-dataset/)
```

**edit .gitmodules file** as suggested in the docs

next:

```
datalad add --to-git .gitmodules
datalad save
datalad publish --to origin
```
