### ISSUE TITLE
CONP datasets name convention required

### ISSUE THREAD

**Issue by gi114** [CONP-PCNO/conp-dataset#234]
## Purpose
Define a naming convention for CONP datasets to clearly express their source, focus and use

## Context
At the moment, dataset names in [this repository](https://github.com/CONP-PCNO/conp-dataset/tree/master/projects) are not consistent, some of them are not expressing the dataset they represent, some of them are long and meaningless 

## Possible Implementation
We could think of a possible prefix-word-suffix syntax, to provide information on the dataset source (prefix) and on a general topic they are related to (word) and, more specific information, on the issue they tackle (suffix)

I would like to open the discussion here to hear from others on this

Thanks

**Comment by PapillonMcGill** [comment]
I do think it is not ours the regulate the way lab, PI, research center, etc name their datasets.

We could have some spelling criteria like letters, digits, hyphen, accented vs non accented chars or no special characters for technical reason but that is about the maximum we should do.

**Comment by emmetaobrien** [comment]
I think we would benefit from names that are clearer than those some of the datasets have now, and less long and unwieldy than, for example, "MRI_and_unbiased_averages_of_wild_muskrats__Ondatra_zibethicus__and_red_squirrels__Tami", which would strike me as more a description than a name (and also looks like it has been truncated somewhere during processing).   Showing a description in the search results page would obviate the need for long and complex names.  I favour recommending, if not necessarily enforcing, naming practices that avoid outputs like the above.

**Comment by PapillonMcGill** [comment]
In that case, yes, it look like they didn't had any name in mind and use the description. In fact the "name" was effectively truncated.
A limit of maybe 50 chars would be appropriate.

As for the details in that "name", they should go it the DATS.json files to be used by search engine.
When we will have hundreds (and even before), searcher won't decide to use a dataset by the name but by what is returned by the query they ran in the search engine.

**Comment by glatard** [comment]
Sounds good but let's also keep in mind that many datasets will be crawled and we have no way to enforce restrictions on names on these platforms (Zenodo, FRDR, OSF). So any unenforceable requirement would mean more human intervention in the data import process.

**Comment by emmetaobrien** [comment]
We cannot enforce those requirements, but is it worth suggesting - for example in the documentation for using Zenodo to set up a dataset for CONP ingestion - good practices for names? I am thinking primarily in terms of people whose choices in putting data on those other platforms are influenced by wanting to see their data in CONP, datasets that are already in another platform are a different case.

**Comment by emmetaobrien** [comment]
Discussed on July 15 2020 and decided to close.
