### ISSUE TITLE
Add different resolution of the BigBrain dataset

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#238]
## Purpose

In bigbrain.loris.ca, there are different resolution/registration available for the BigBrain dataset. They will need to be imported in CONP.

## Context

There are many big brain datasets available with different resolution and registration technics used. Currently, the BigBrain dataset only contains the 40um 3D blocks.

## Possible Implementation 

Two possibilities were discussed during the CONP dev call of March 25th, 2020:

1. Add the different versions (aka resolution/registration) as subdatasets of the current BigBrain dataset

2. Create a dataset per resolution/registration

Will probably aim toward solution 1. Later, we will need to make BigBrain a subdataset of the processed dataset.

## Related issues 

https://github.com/CONP-PCNO/conp-dataset/issues/230

**Comment by cmadjar** [comment]
List of what is available in bigbrain.loris.ca:

### 3-D Volumes (MINC and NIfTI files for all)

- Registration MNI ICBM 152 Space
  - Encoding 16-bit gray scale unsigned short
     - 4 volumes of different resolutions (100, 200, 300 & 400um) 
  - Encoding 8-bit gray scale unsigned short
      - 4 volumes of different resolutions (100, 200, 300 & 400um) 
      - ICBM 2009b Symmetric Template 500um

- Registration MNI ADNI Space
  - Encoding 16-bit gray scale unsigned short
     - 4 volumes of different resolutions (100, 200, 300 & 400um) 
  - Encoding 8-bit gray scale unsigned short
      - 4 volumes of different resolutions (100, 200, 300 & 400um) 

- Registration Histological Space
  - Encoding 16-bit gray scale unsigned short
     - 5 volumes of different resolutions (100, 200, 300, 400 & 1000um) 
  - Encoding 8-bit gray scale unsigned short
      - 5 volumes of different resolutions (100, 200, 300, 400 & 1000um) 

### 3-D Surfaces (Obj and GifTi for all)

- Registration MNI ICBM 152 Space (ICBM 2009b Nonlinear Symmetric)
  - Grey left hemisphere (Obj and GifTi formats)
  - Grey right hemisphere (Obj and GifTi formats)
  - White left hemisphere (Obj and GifTi formats)
  - White right hemisphere (Obj and GifTi formats)

- Histological Space
  - Grey left hemisphere (Obj and GifTi formats)
  - Grey right hemisphere (Obj and GifTi formats)
  - White left hemisphere (Obj and GifTi formats)
  - White right hemisphere (Obj and GifTi formats)

### 3-D Classified Volumes

- Registration MNI ICBM 152 Space (ICBM 2009b Nonlinear Symmetric)
      - 5 volumes of different resolutions (100, 200, 300, 400 & 1000um) 

- Registration Histological Space
      - 5 volumes of different resolutions (100, 200, 300, 400 & 1000um)

**Comment by cmadjar** [comment]
I listed what is in LORIS when navigating through the LORIS website.

When I looked at the FTP website, I see that there are 2 releases: 2013 and 2015. There appears to be also more dataset types (like ROI, MRI, ...)
@glatard any suggestion on what we should do?

**Comment by cmadjar** [comment]
BigBrain FTP site: ftp://bigbrain.loris.ca/

**Comment by glatard** [comment]
Hi @cmadjar, I think option 1 is the way to go indeed. We could have 1 dataset with a sub-dataset for each resolution, data type (16/8 bits), and registration. I think surfaces and classified volumes are derived data though, so they could go separately. 

@jbpoline and @samirdas may want to chime in here.

**Comment by emmetaobrien** [comment]
@glatard: that will be straightforward to do and I can proceed whenever the decision is confirmed; still  also need to know whether to proceed with the 2013 or 2015 release, or both.

**Comment by glatard** [comment]
Unless the Khan Lab's dataset uses the 2013 release, I would suggest sticking to the 2015 one. Let's consider the decision confirmed by today end of day if there is no objection by then.

**Comment by emmetaobrien** [comment]
Both of the Khan lab BigBrain datasets we currently have are annotated as from the 2015 release.

**Comment by samirdas** [comment]
Sounds good to me. :)

**Comment by emmetaobrien** [comment]
I have processed the 3D Volumes and 3D Classified Volumes data, which will be made available as part of https://github.com/CONP-PCNO/conp-dataset/pull/239, and am looking into the 3D Surfaces next.
