### ISSUE TITLE
Convention for hosting datasets in this repository

### ISSUE THREAD

**Issue by stronics** [CONP-PCNO/conp-dataset#26]
I think it would beneficial that going forward we agree on the convention for 'how' we will organize and host datasets. Currently, datasets are either under `projects` or under `investigators`.  Under this convention, what differentiates hosting datasets under `projects` vs `investigators`? If we take the example of Simon's Phantom dataset, should it be under `projects` or under `investigators`? 

Another possibility would be to adopt the flat convention that [datasets.datalad.org](http://datasets.datalad.org/) uses, which is just a [list](https://github.com/datalad/datasets.datalad.org) of git submodules:

![Screen Shot 2019-04-17 at 10 30 05 AM](https://user-images.githubusercontent.com/1534575/56296079-cdf5b300-60fb-11e9-90f0-153a2f0f6c13.png)

On the search part, I just need to point to the right path. 

Thoughts @Park-Patrick @jbpoline @glatard @jbpoline @shots47s @samirdas ?

**Comment by glatard** [comment]
Initially I thought that it would make sense to separate individual people from larger projects, in particular when it comes to derived data. For instance, I'd like to upload my data processing experiments, e.g., to be able to share the results of a paper, but that may not fall under a larger project like the ones listed here. I think it's important that researchers have a place to put their derived or raw data, and we might want to separate it from the more established platforms. But ultimately I don't really mind the data structure if there is a good argument to change it.

**Comment by emmetaobrien** [comment]
This issue was resolved by https://github.com/CONP-PCNO/conp-dataset/pull/171
