### ISSUE TITLE
Dev branch

### ISSUE THREAD

**Issue by mathdugre** [CONP-PCNO/conp-dataset#261]
## Purpose
Creating a `dev` branch would allow an easier workflow for development.
For example, the test for authenticated datasets is skipped on PR for security reason.

## Possible Implementation (optional)
Point PR related to development to a `dev` branch.

## Related issues (optional)
#260 Fails due to the handling of authentication explained in #197

**Comment by glatard** [comment]
After discussion, it's unclear how the `git-annex` branch should be managed when we have a `master` and a `develop` branch in the dataset. This needs further investigation.

**Comment by cmadjar** [comment]
@mathdugre @glatard I am not sure how this would be feasible because of the git-annex branch. Maybe we should close this issue?

**Comment by mathdugre** [comment]
@cmadjar , I agree. I will close the issue for now. If the needs be, we can reopen it later.
