### ISSUE TITLE
Khanlab/HCPUR100-Template fails to download some files

### ISSUE THREAD

**Issue by mathdugre** [CONP-PCNO/conp-dataset#263]
## Description
When trying to retrieve the files for _Khanlab/HCPUR100-Template_, some of them fail to download.

### Steps to reproduce:
```bash
docker run --rm -it mathdugre/conp-dataset:v1
python -m venv venv
. venv/bin/activate
export PATH=~/git-annex.linux/:$PATH
git clone https://github.com/CONP-PCNO/conp-dataset.git
cd conp-dataset
pip install -r requirements.txt -r tests/requirements.txt -r scripts/dats_validator/requirements.txt
datalad install -r .
cd projects/Khanlab/HCPUR100-Template/
datalad get . | grep -i error 
```
### Output:
```bash
[...]
get(error): sub-HCPUR100/anat/sub-HCPUR100_t2w.mif (file) [verification of content failed]
get(error): sub-HCPUR100/anat/sub-HCPUR100_t1w.mif (file) [verification of content failed]
get(error): sub-HCPUR100/anat/sub-HCPUR100_t2w.nii.gz (file) [verification of content failed]
get(error): sub-HCPUR100/anat/sub-HCPUR100_t1w.nii.gz (file) [verification of content failed]
get(error): sub-HCPUR100/dti/sub-HCPUR100_md.nii.gz (file) [download failed: Requested range not satisfiable
get(error): sub-HCPUR100/dti/sub-HCPUR100_rd.mif (file) [download failed: Requested range not satisfiable
get(error): sub-HCPUR100/dti/sub-HCPUR100_ad.nii.gz (file) [download failed: Requested range not satisfiable
get(error): sub-HCPUR100/csd/sub-HCPUR100_gmresponse.txt (file) [download failed: Requested range not satisfiable
get(error): sub-HCPUR100/dti/sub-HCPUR100_md.mif (file) [download failed: Requested range not satisfiable
  get (error: 9)
```

**Comment by glatard** [comment]
does this dataset pass the tests?

**Comment by mathdugre** [comment]
@glatard, yes it does. 
I found this bug when I implemented my greedy approach in #254 .

**Comment by emmetaobrien** [comment]
I have tried downloading the source dataset directly from https://github.com/khanlab-datasets/HCPUR100-Template and am getting failures:

` [ERROR  ] not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin) [get(/data/temp-datasets/HCPUR100-Template/sub-HCPUR100/anat/sub-HCPUR100_t1w.nii.gz)]
get(error): sub-HCPUR100/anat/sub-HCPUR100_t1w.nii.gz (file) [not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin) [get(/data/temp-datasets/HCPUR100-Template/sub-HCPUR100/anat/sub-HCPUR100_t2w.mif)]
get(error): sub-HCPUR100/anat/sub-HCPUR100_t2w.mif (file) [not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin) [get(/data/temp-datasets/HCPUR100-Template/sub-HCPUR100/anat/sub-HCPUR100_t1w.mif)]
get(error): sub-HCPUR100/anat/sub-HCPUR100_t1w.mif (file) [not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin) [get(/data/temp-datasets/HCPUR100-Template/sub-HCPUR100/anat/sub-HCPUR100_t2w.nii.gz)]
get(error): sub-HCPUR100/anat/sub-HCPUR100_t2w.nii.gz (file) [not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin)]
action summary:
  get (error: 4)`

That looks like wherever the Khan lab originally built their links to might have changed or been removed.

Also, and I am not sure whether this is related, when I download https://github.com/khanlab-datasets/HCPUR100-Template the datalad symlinks appear to be coming up with execute permission for all, which does not make any sense to me.

**Comment by emmetaobrien** [comment]
I contacted Jason Kai and determined that these files had been updated at the Khan lab, but not in their github repository; Jason since updated the repository and I have merged those updates, and the files now appear to be working.

**Comment by glatard** [comment]
@mathdugre do you confirm that this dataset is now functional?

**Comment by mathdugre** [comment]
@glatard, the dataset is working properly now 👍
