### ISSUE TITLE
Fail to download multicenter-phantom

### ISSUE THREAD

**Issue by mathdugre** [CONP-PCNO/conp-dataset#264]
## Description

The current build is failing, in part, since there is problem to retrieve files for the _multicenter-phantom_ dataset.

### Steps to reproduce:
```bash
docker run --rm -it mathdugre/conp-dataset:v1
python -m venv venv
. venv/bin/activate
export PATH=~/git-annex.linux/:$PATH
git clone https://github.com/CONP-PCNO/conp-dataset.git
cd conp-dataset
pip install -r requirements.txt -r tests/requirements.txt -r scripts/dats_validator/requirements.txt
datalad install -r .
cd projects/multicenter-phantom
datalad get .
```

**Sample output:**
```bash
[...]
get(error): phantom_999876_MNI_20130903_t1w_002.mnc (file) [not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin)]
get(error): phantom_999876_MNI_20110721_t1w_001.mnc (file) [not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin)]
action summary:
  get (error: 2710)
```

#260 Reports a test failure partially due to this issue.

**Comment by mathdugre** [comment]
@cmadjar, I was informed during a meeting with @glatard that you might know who was responsible of this dataset

**Comment by cmadjar** [comment]
I think @emmetaobrien created the datalad dataset for the multi-center phantom.

If you need an account on the LORIS instance of that dataset though, I can help with that. Just let me know

**Comment by emmetaobrien** [comment]
I have recrawled [phantom.loris.ca](url) and updated the dataset with regenerated links, and am currently seeing inconsistent behaviour where the new links are downloading correctly for me but are still failing for @cmadjar; will look into this further.
