### ISSUE TITLE
Khanlab/BigBrainMRICoreg file system check failure.

### ISSUE THREAD

**Issue by mathdugre** [CONP-PCNO/conp-dataset#302]
Running `git annex fsck` on the dataset results in failures.

## Current Behavior

```bash
Cmd('git') failed due to: exit code(1)
  cmdline: git annex --fast --json --json-error-messages --quiet fsck
  stderr: '  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009asym/BigBrainHist-to-ICBM2009asym-nonlin.xfm
  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009asym/BigBrainHist-to-ICBM2009asym-nonlin_grid_0.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009asym/BigBrainHist-to-ICBM2009asym-nonlin_grid_1.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009asym/BigBrainHist-to-ICBM2009asym-nonlin_grid_2.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009asym/BigBrainHist-to-ICBM2009asym-nonlin_grid_3.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009sym/BigBrainHist-to-ICBM2009sym-nonlin.xfm
  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009sym/BigBrainHist-to-ICBM2009sym-nonlin_grid_0.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009sym/BigBrainHist-to-ICBM2009sym-nonlin_grid_1.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009sym/BigBrainHist-to-ICBM2009sym-nonlin_grid_2.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-ICBM2009sym/BigBrainHist-to-ICBM2009sym-nonlin_grid_3.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-PD25/BigBrainHist-to-PD25-nonlin.xfm
  ** No known copies exist of HistTransformation/BigBrainHist-to-PD25/BigBrainHist-to-PD25-nonlin_grid_0.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-PD25/BigBrainHist-to-PD25-nonlin_grid_1.mnc
  ** No known copies exist of HistTransformation/BigBrainHist-to-PD25/BigBrainHist-to-PD25-nonlin_grid_2.mnc
git-annex: fsck: 14 failed'
```

see [CircleCI logs](https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/103/workflows/bba515cf-6ae5-4bda-b0c1-bbc1210421d4/jobs/185/tests).

## Environment

see [tests documentation](https://github.com/CONP-PCNO/conp-dataset/tree/master/tests#Dependencies).

**Comment by emmetaobrien** [comment]
I have had mail from @kaitj confirming that this dataset has not been updates since February and that running `git annex fsck` at his end does not give any errors.

**Comment by glatard** [comment]
@kaitj, could you let us know which version of git-annex you are using?

**Comment by kaitj** [comment]
@glatard 7.20190819+git2-g908476a9b-1~ndall+1 (from git-annex-standalone) when I had run the command yesterday.

Also just checked with 6.20180227 (from git-annex; also did not give any errors)

**Comment by emmetaobrien** [comment]
when I `datalad install` this dataset, I then get:

```
git annex get *0.mnc
get BigBrainHist-to-ICBM2009asym-nonlin_grid_0.mnc (not available)
  No other repository is known to contain the file.

  (Note that these git remotes have annex-ignore set: origin)
failed
git-annex: get: 1 failed
```

My installed version of git-annex is **8.20200309**

**Comment by glatard** [comment]
@emmetaobrien the behavior you got is consistent with the one in the tests: https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/141/workflows/b5d6b149-4798-497b-8275-e49653d63862/jobs/256

@kaitj could it be that you have a local copy of the files somehow? And if so, could you start from a fresh clone of the data repo?

**Comment by kaitj** [comment]
Just an update - dug into this a little more this morning. The local copies had the storage locations via `git annex whereis`, however the clones (both in `conp-dataset` and `khanlab-datasets`) seem to be lacking these URLs. Additionally, when the repo's are cloned to one disk, the URLs are available (same disk as where the `khanlab-datasets` is stored), but when cloned to a separate disk, the URLs are missing. Did run an fsck on a fresh clone the other day, but must have done it on that same disk.

Working on it currently, and will update / PR when fixed. Trying to sync the git annex to see if that fixes it (though running into issues). Open to suggestions / comments.

**Comment by kaitj** [comment]
Ended up reinitializing the repo and made the PR at `conpdatasets` (https://github.com/conpdatasets/BigBrainMRICoreg/pull/4). 

I think my previous PR (in March) to add the new files to the dataset modified the annex paths, which broke when running `datalad install` in a new environment resulting in the errors above.
