### ISSUE TITLE
preventad-open file system check fails.

### ISSUE THREAD

**Issue by mathdugre** [CONP-PCNO/conp-dataset#303]
Running `git annex fsck` on the dataset results in failures.

## Current Behavior

```bash
Cmd('/home/circleci/git-annex.linux/git') failed due to: exit code(1)
  cmdline: /home/circleci/git-annex.linux/git annex --fast --json --json-error-messages --quiet fsck
  stderr: '  ** No known copies exist of .datalad/metadata/objects/4d/cn-b056d3d8a2d5ded0db5c1fc92b379f.xz
  These dead repositories used to have copies
  	37bad72c-0d9f-4b84-8a29-3b17e0101050
  ** No known copies exist of .datalad/metadata/objects/4d/ds-b056d3d8a2d5ded0db5c1fc92b379f
  These dead repositories used to have copies
  	37bad72c-0d9f-4b84-8a29-3b17e0101050
git-annex: fsck: 2 failed'
```

see [CircleCI logs](https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/103/workflows/bba515cf-6ae5-4bda-b0c1-bbc1210421d4/jobs/185/tests).

## Environment

see [tests documentation](https://github.com/CONP-PCNO/conp-dataset/tree/master/tests#Dependencies).

**Comment by emmetaobrien** [comment]
Testing now;  I am seeing those failures too. Is there a straightforward way in CircleCI to tell which datafile those files refer to ?  I've been poking around with git-annex and not finding a simple way to do so.

**Comment by mathdugre** [comment]
The files seem to be related to the dataset metadata, however, I'm unaware of a way to extract more information about this error message.

**Comment by mathdugre** [comment]
@emmetaobrien, It looks like the metadata for the dataset were not updated when it got restructured. From my understanding of DataLad internals, the last time the metadata were changed would be [here](https://github.com/conpdatasets/preventad-open/commit/c97a626e687007e7d92e3d4478d374952ad2c14c) which dates to when the dataset files were not structured.

```bash
(venv) circleci@c0ccdde4a124:~/conp-dataset/projects/preventad-open$ datalad metadata
Total (0 ok, 2 failed out of 2):   0%|                                                              | 0.00/506M [00:00<?, ?B/s]
[WARNING] Running get resulted in stderr output: git-annex: get: 2 failed
 
[ERROR  ] not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin) [get(/home/circleci/conp-dataset/projects/preventad-open/.datalad/metadata/objects/4d/cn-b056d3d8a2d5ded0db5c1fc92b379f.xz)] 
[ERROR  ] not available; No other repository is known to contain the file.; (Note that these git remotes have annex-ignore set: origin) [get(/home/circleci/conp-dataset/projects/preventad-open/.datalad/metadata/objects/4d/ds-b056d3d8a2d5ded0db5c1fc92b379f)] 
```

**Comment by emmetaobrien** [comment]
The only other dataset we have with content in `.datalad/metadata/objects` is multicenter-phantom, and while I haven't seen test results complain about it, the links it contains do not work either:
```

eaobrien@datalad-dev:/data/temp-datasets/conp-dataset/projects/multicenter-phantom/.datalad/metadata/objects/da$ git annex whereis *
whereis cn-7ed29a1ab7a15cca3f98b8a5a424bc.xz (0 copies) failed
whereis ds-7ed29a1ab7a15cca3f98b8a5a424bc (0 copies) failed
git-annex: whereis: 2 failed
```

Looking at the date of those commits (13 months ago in both datasets), I think we may be looking at remnants of an unsuccessful or at least incomplete early experiment with a different part of the datalad system.  I am not aware of anything we currently do that uses the datalad metadata sources; it might be worth looking at again at some point, but that looks non-trivial, so maybe we just want to do without them for now ?

**Comment by mathdugre** [comment]
I agree that for now we might want to ignore them.
I will draft a pull request to address this issue.

**Comment by cmadjar** [comment]
I wonder if this is linked to an issue I am having when creating the BIDS PREVENT-AD dataset: I always get an info displayed by DataLad telling me that the metadata could not be added to the images.

Could this have been the case when PREVENT-AD was originally crawled too? Or maybe totally unrelated...
