### ISSUE TITLE
Procedures for dataset decay over time.

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#309]
Arising from a conversation with @glatard and @joeyzhou98 on Slack earlier today.

It seems like a good idea to define procedures for how we will deal with maintaining and/or decommissioning CONP data sources when the project that generated the data comes to an end.  We have a defined `contact` field in the DATS model which should provide a point of contact for issues and queries during the lifetime of a project, and are requiring that of new data submissions, but how long that will extend afterwards is not predictable.  @jbpoline, I believe we have talked about a possible benefit to CONP being providing a home for useful small datasets after the original source expires, but I am not finding any concrete plans for how we might go about that.

@glatard proposed that we:
 -   When a dataset is crawled, make sure that there is a contact point for the author, i.e., ensure the presence of that info in Zenodo or OSF
 -   Define a procedure to remove broken datasets when authors aren't responsive.

I am in agreement though with the caveat that I don't think we necessarily want to be too stringent about defining 'broken'.  I can see there still being potential value to a no-longer-maintained dataset that contains some useful data even if not all of it works any more, and I can see that as a plausible future possibility with datasets such as https://github.com/conpdatasets/mm_neo_atlas/ (specialised, not under active development, relatively small, connecting to files at multiple locations) so maybe we might want a status marker of some sort that we could display in the interface, saying something like "not actively maintained" or "project concluded".

**Comment by cmadjar** [comment]
https://github.com/CONP-PCNO/conp-portal/issues/301

**Comment by cmadjar** [comment]
Will be discussed on Wednesday to elaborate a plan for this issue.

**Comment by cmadjar** [comment]
Could leverage the stale Github action. Whenever a dataset is flagged as broken by our test suite, create an issue. When the issue gets flagged as stale and is eventually automatically broken, then we can either remove the dataset or unstale the issue.
