### ISSUE TITLE
Intracellular_Recordings_of_Murine_Neocortical_Neurons

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#321]
DATS file doesn't pass validation:
```

_ TestDataset.test_has_valid_dats[projects/Intracellular_Recordings_of_Murine_Neocortical_Neurons] _
 
Dataset projects/Intracellular_Recordings_of_Murine_Neocortical_Neurons doesn't contain a valid DATS.json.
 
------------------------------ Captured log call -------------------------------
 
ERROR    scripts.dats_validator.validator:validator.py:48 1 Validation error in distributions.0.size: '9.1' is not of type 'number'
 ```

See test build at https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/245/workflows/6b854ba7-56f6-4894-848b-f869de4ee4fe/jobs/459/parallel-runs/1?filterBy=FAILED

This is most likely coming from the OSF crawler. @joeyzhou98, could you have a look?

**Comment by joeyzhou98** [comment]
@glatard here is the fixed dataset PR, https://github.com/CONP-PCNO/conp-dataset/pull/327. It should fix the DATS validation failing, let me know if there are any more problems

**Comment by glatard** [comment]
tests pass now, thanks!
