### ISSUE TITLE
Prevent-AD fails download

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#322]
* Test build: https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/246/workflows/30878278-9094-4aec-85e1-ab863dfe7ef9/jobs/461/parallel-runs/0?filterBy=FAILED
* Standard error:
```
______________ TestDataset.test_download[projects/preventad-open] ______________
 
The dataset timed out after 120 seconds before retrieving a file. Cannot to tell if the download would be sucessful.
 
1322140/NAPEN00/visit.json has size of inf Bytes.
 
----------------------------- Captured stdout call -----------------------------
 
projects/preventad-open/1322140/NAPEN00/visit.json
 ```
* Help requested from: @cmadjar @emmetaobrien

**Comment by mathdugre** [comment]
Hi @glatard , This issue seems to be due to wrong authentication to prevent-ad:
```
tests/test_projects_preventad-open.py::TestDataset::test_download[projects/preventad-open] Authenticated access to *********************************************/candidates/1322140/NAPEN00 has failed.
Do you want to enter other credentials in case they were updated? (choices: yes, no): FAILED [ 86%]
```

**Comment by cmadjar** [comment]
Indeed, this is most probably an authentication issue as I am able to download that file. Not sure how to fix that for Circle CI though since the username and password is asked again after a few days I think.

**Comment by glatard** [comment]
I just updated the username used in the tests (I think it was wrong), let's see if it works now.

**Comment by glatard** [comment]
(it doesn't...)

**Comment by cmadjar** [comment]
looks like preventad-open is fine now. But preventad-open-bids is still failing.

![Screen Shot 2020-06-05 at 1 47 35 PM](https://user-images.githubusercontent.com/1402456/83907283-2be7be80-a733-11ea-82a3-771967c97f83.png)

how did you fix it?

**Comment by glatard** [comment]
oh, so I've been confused between the 2 preventad datasets and my credentials fix actually worked :) Can I use the same credentials (LORIS endpoint, username and password) to access preventad in bids?

**Comment by glatard** [comment]
let's follow up on that in #330

**Comment by cmadjar** [comment]
I am not sure if I believe the circleci status, right now, all datasets are in a warning state.

When I checked PREVENT-AD vs PREVENT-AD BIDS, both were failing. But then magically PREVENT-AD was working but that was this afternoon, way after the credential fix you did this morning. 

Did you do anything this afternoon? If not, not sure why sometimes it fails and sometimes it works...
