### ISSUE TITLE
Datasets with no hash

### ISSUE THREAD

**Issue by mandana-mazaheri** [CONP-PCNO/conp-dataset#337]
Not `MD5E `hashes in symlinks for some data files

I found that there are three CONP datasets:

> Learning_Naturalistic_Structure__Processed_fMRI_dataset
> SIMON-dataset
> openpain

which although in `.gitattributes` for all of them `annex.backend=MD5E`, in symlink of all data files there is no file hash as `MD5E`.

## Expected Behavior

It would be much helpful if for all datasets we have access to file hashes as `MD5E` as all datasets in this repository. I explained the details in the next part.

**For example :** suppose a file in
`BigBrainHippoUnfold/BIDS_downsampled/HippUnfold/sub-bbhist/anat/sub-bbhist_hemi-L_label-HippUnfold_srcsnk-AP_PhiMap.nii.gz `  when we open that in github or read as a .txt file in local machine (before downloading) we see 
`../../../../.git/annex/objects/2W/41/MD5E-s605794--3b0b001353ae7d087758c104285f78f6.nii.gz/MD5E-s605794--3b0b001353ae7d087758c104285f78f6.nii.gz` 
which contains the `MD5E` of this file, it is really helpful when we need information about datasets but we do not want to download all files.

## Current Behavior

Currently, when we install these datasets, before downloading, we can read the symlink and for all of these files the git-annex backend is `URL`, [https://git-annex.branchable.com/backends/](url) 

**For Example:**  suppose a file in this directory ` SIMON-dataset/data_BIDS/sub-032633/ses-001/anat/sub-032633_ses-001_run-1_T1w.nii.gz ` when we open that in github or read as a .txt file in local machine (before downloading) we see
 `../../../../.git/annex/objects/Q6/wp/URL-s10939870--https&c%%amnesia.cbrain.mcgill.c-2031f69b0877d6d5d94ceffc09058988/URL-s10939870--https&c%%amnesia.cbrain.mcgill.c-2031f69b0877d6d5d94ceffc09058988` 

## Context (optional)

We have a database containing all files in all CONP datasets which would be the source of a recommendation system for CONP-datasets and the Zenodo pipelines. Without this information, we are losing important datasets' information and the recommendation system would not be as accurate as we expect.

**Comment by cmadjar** [comment]
@emmetaobrien could you investigate if that is still the case? Thank you!

**Comment by emmetaobrien** [comment]
This is still the case for Learning_Naturalistic_Structure__Processed_fMRI_dataset, SIMON-dataset and all six openpain datasets.

Looking at the git-annex documentation (https://git-annex.branchable.com/backends/) symlinks of this form are generated when the file content is not available for hashing at the time they were added to the repository, so they would need to be removed and re-added.

**Comment by cmadjar** [comment]
This will be discussed at the next CONP-dev call. Looking at @emmetaobrien's comment above, it would appear that all the crawled dataset would have that issue, in addition to SIMON and all 6 openpain datasets.

Proposal to recrawl everything without the `--fast` option so MD5E hashes can be present in the dataset. 

For the crawler datasets, will need to modify both crawlers to remove the `--fast` option and then drop the file after the download has been completed to avoid taking up too much disk space. Then, will need to recrawl all the datasets.

**Comment by emmetaobrien** [comment]
Note that all datasets generated by crawling OSF or Zenodo also have symlinks of this form.

**Comment by emmetaobrien** [comment]
I am currently testing `git annex migrate` to update the link format for one of the openpain datasets.

**Comment by cmadjar** [comment]
@emmetaobrien Correct me if I am wrong but I think that all the manual datasets have been fixed, right? The only other dataset that do not have hashes with files are the crawlers' datasets for which we will rely on the versioning of the crawled platform (Zenodo, OSF for now).

If that is the case, maybe this can be closed?

**Comment by emmetaobrien** [comment]
Yes, I believe this is the case. For reference, that is the SIMON and openpain datasets recrawled; I was holding off on closing this issue until @glatard updated all the openpain datasets and I have finished updating the conpdatasets copies and update conp-dataset, for them, which I am in the middle of doing now.

**Comment by emmetaobrien** [comment]
All the manually generated datasets to which this issue applies are now updated.
