### ISSUE TITLE
Remove the docs directory in conp-dataset and move the docs to the conp-documentation repo

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#351]
## Purpose

Currently, the content of the `docs` directory in `conp-dataset` is old graphs and pictures. During the CONP dev meeting of July 2nd, 2020, it was proposed to move the content of that repository into the conp-documentation repository and remove the `docs` directory of the `conp-dataset`.

**Comment by emmetaobrien** [comment]
The relevant file was moved to conp-documentation in https://github.com/CONP-PCNO/conp-documentation/pull/43, and the docs directory is removed from conp-datasets in https://github.com/CONP-PCNO/conp-dataset/pull/347.

**Comment by cmadjar** [comment]
Thank you @emmetaobrien! Closing the issue as this is resolved now.
