### ISSUE TITLE
Integrate OBI datasets

### ISSUE THREAD

**Issue by zxenia** [CONP-PCNO/conp-dataset#353]
## Purpose
The issue to track tasks, discussion, and progress on the OBI datasets integration.

**Comment by cmadjar** [comment]
Discussion from the CONP dev meeting on July 8th, 2020:

- There are 40 DATS files with no access to the data at the moment
- Only 3 DATS files + 3 README will be on the repo and the other ones will be linked to the 3 original datasets. 
  - Mouse MRI
  - Long term phantom quality assurance
  - Neurodevelopmental disorder
- README will contain information on how to get the data on BrainCode.

**Comment by cmadjar** [comment]
@zxenia Are there more OBI datasets coming up? Is this issue resolved?

**Comment by zxenia** [comment]
@cmadjar There is one more dataset, I am going to add it this week.

**Comment by cmadjar** [comment]
@zxenia just to be sure. This is now resolved, right?

**Comment by zxenia** [comment]
@cmadjar Yes, they are all integrated into the portal now.
