### ISSUE TITLE
preventad-open fails to download

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#356]
* Test build: 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/543/workflows/beef4f4c-d741-4a8c-90bb-85a59df7eb19/jobs/1074

* Standard error:
```
______________ TestDataset.test_download[projects/preventad-open] ______________
 
The dataset timed out after 120 seconds before retrieving a file. Cannot to tell if the download would be sucessful.
 
1322140/NAPEN00/visit.json has size of inf Bytes.
 
----------------------------- Captured stdout call -----------------------------
 
projects/preventad-open/1322140/NAPEN00/visit.json
 ```

* Help requested from:
@cmadjar @emmetaobrien

**Comment by cmadjar** [comment]
@glatard I was able to download that file manually on my computer:
```
(datalad_python3) preventad-open $ datalad get 1322140/NAPEN00/visit.json
Authenticated access to https://openpreventad.loris.ca/api/v0.0.3-dev/candidates/1322140/NAPEN00 has failed.
Do you want to enter other credentials in case they were updated? (choices: yes, no): yes

You need to authenticate with 'loris-prevent-ad' credentials. https://openpreventad.loris.ca/api/v0.0.3-dev/login provides information on how to gain access
user: admin

password: 
password (repeat): 
get(ok): 1322140/NAPEN00/visit.json (file) [from datalad...]  
```

Could this be that the token expired at some point during testing and somehow made Circle CI crash?

Not sure what else to try on my end...

**Comment by glatard** [comment]
Trying to login with the password used by CircleCI, I realized that LORIS required its renewal:
![Screenshot from 2020-07-15 10-42-13](https://user-images.githubusercontent.com/5174953/87559510-632d8180-c688-11ea-930b-17f3aa3919c5.png)
This is likely to be the reason for authentication issues. 

I re-generated a password and added it to CircleCI, let's see if it fixes things.

Note to self: if authentication still fails, it could be due to the presence of special characters in the password, as it is passed through an env var to the test script.

**Comment by glatard** [comment]
yep, updating the password fixed it: https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/584/workflows/f5311617-b8d3-4a18-bcd7-59f28e833067/jobs/1163/tests
