### ISSUE TITLE
mcgill-emc-rna-seq-experiment fails DATS validation

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#357]
* Test build: 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/543/workflows/beef4f4c-d741-4a8c-90bb-85a59df7eb19/jobs/1074/tests

* Standard error:
```
___ TestDataset.test_has_valid_dats[projects/mcgill-emc-rna-seq-experiment] ____
 
Dataset projects/mcgill-emc-rna-seq-experiment doesn't contain a valid DATS.json.
 
------------------------------ Captured log call -------------------------------
 
ERROR    scripts.dats_validator.validator:validator.py:48 1 Validation error in hasPart.0: 'distributions' is a required property
 
ERROR    scripts.dats_validator.validator:validator.py:48 2 Validation error in hasPart.1: 'distributions' is a required property
 ```

* Help requested from:
@emmetaobrien

**Comment by emmetaobrien** [comment]
This is another example of a `dataset `where the `hasPart` entries do not contain all our required distribution fields.  This particular one comes from @zxenia, whom I have contacted about it and who is taking action to fix it.

**Comment by emmetaobrien** [comment]
This is fixed with https://github.com/CONP-PCNO/conp-dataset/pull/359.
