### ISSUE TITLE
conp-dataset-MRI_and_unbiased_averages_of_wild_muskrats__Ondatra_zibethicus__and_red_squirrels__Tami timing out

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#362]
* Test build:
 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/579/workflows/bc1257f2-d763-40d6-9e7f-7e27bb9c4646/jobs/1146

* Standard error:

The dataset timed out after 120 seconds before retrieving a file. Cannot to tell if the download would be sucessful.
data_release/muskrat/demo.csv has size of inf Bytes

* Help requested from:

@glatard, @joeyzhou98, @cmadjar.

**Comment by emmetaobrien** [comment]
Edited to correct cut and paste error in the initial description text.

**Comment by joeyzhou98** [comment]
I will take a look at it tonight

**Comment by emmetaobrien** [comment]
This has not been recurring in monitoring messages since so I think it may have been a transient connection issue.

**Comment by glatard** [comment]
this is passing now, most likely a transient issue indeed.

**Comment by emmetaobrien** [comment]
https://github.com/CONP-PCNO/conp-dataset/issues/332

**Comment by emmetaobrien** [comment]
And it is now happening again - https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/588/workflows/890eb334-2d9a-4830-97b8-ff8d40ac636b/jobs/1169.

**Comment by cmadjar** [comment]
Is this still happening? I do not see that dataset in the latest tests.

**Comment by glatard** [comment]
Tests seem to be passing now, feel free to re-open if there are still issues.
