### ISSUE TITLE
Support crawling private datasets on OSF

### ISSUE THREAD

**Issue by joeyzhou98** [CONP-PCNO/conp-dataset#364]
## Purpose
To allow users to upload restricted datasets on OSF and let the crawler retrieve them to add to conp-datasets with restricted access

**Comment by cmadjar** [comment]
Deadline: end of August.

Thank you @joeyzhou98 for creating the issue!

**Comment by cmadjar** [comment]
@joeyzhou98 I believe https://github.com/CONP-PCNO/conp-dataset/pull/387 resolved this issue, correct?

**Comment by joeyzhou98** [comment]
@cmadjar indeed, closing this
