### ISSUE TITLE
Datasets in status "Warning"

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#365]
In the portal, several datasets regularly have the status "Warning" associated with an orange badge.

![Screenshot from 2020-07-15 09-58-06](https://user-images.githubusercontent.com/5174953/87554141-c4058b80-c681-11ea-8f0a-a854c0034eca.png)

## Expected Behavior

Status should be "Working" or "Broken" most of the time. 

## Current Behavior

The "Warning" status is commonly encountered.

## Context 

- This was observed several times in the past months.
- Underlying reason is not precisely known yet
- Possible reasons:
  - Tests time out after 10 min, for instance because of no output. None of the remaining tests are evaluated. This is what happened here:

![Screenshot from 2020-07-15 09-55-52](https://user-images.githubusercontent.com/5174953/87557971-89522200-c686-11ea-8cdf-b0978f51c352.png)

 - Status badges do not refer to the latest occurrence of the tests

## Possible fixes
- Change status name to "Unknown" instead of "Warning", put badge in grey instead of orange.
- Increase timeout
- Increase the frequency of badge updates in portal

**Comment by cmadjar** [comment]
@glatard I came across the code displaying the badges yesterday when working on adding publications to the dataset page. I picked the first possible fix you mentioned and sent a PR where I tagged you. 

Let me know what you think.

**Comment by cmadjar** [comment]
Resolved by attached PR
