### ISSUE TITLE
Proposal: increase the granularity of "CONP_status"

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#366]
## Purpose

There is at the moment no consistent location in the DATS.json file specifying the institution providing data, as the `authors` and `creators` fields support a variety of formats (values can be individuals, institutions, or projects/consortia).  

## Context

The utility for this information is in answering questions (e.g. from funding bodies) concerning how many of the datasets available in CONP came from Quebec, from Montreal, from McGill etc. 

## Possible Implementation (optional)

Rather than adding yet another new required field to our DATS schema, it is suggested that the range of values for `CONP_status` field be broadened to allow answering the questions mentioned above.  Suggested values might then include "CONP-McGill" for CONP-funded datasets generated at McGill, "CONP-Montreal" for CONP-funded datasets generated at other institutions in Montreal, "Canadian-McGill" if we include datasets generated in McGill outside the purview of CONP, and so on.

CONP_status is currently used in the CONP portal to mark individual datasets with a Canadian flag as appropriate.  This proposed revision will support that behaviour as before, and will allow for representation of origin in more detail (e.g. Montreal city flag badges) if that were wanted, but the principal envisioned use is for answering questions from outside.  

To assess the viability of this proposal requires a) determining more specifically the range of questions that could be answered this way, and b) establishing a range of values that answer those questions satisfactorily.  Once that is done, implementation is a straightforward matter of updating one field in all existing DATS.json files. A defined list of values here could also serve as a pull-down list for populating the `CONP-status` field in the DATS.json population GUI.

**Comment by cmadjar** [comment]
`CONP_status` field value proposal to be discussed:
- CONP-McGill (for CONP-funded datasets from McGill University)
- Canadian-McGill (for non-CONP-funded datasets from McGill University)
- CONP-<City_name> (for CONP-funded datasets)
- Canadian-<City_name> (for non-CONP-funded datasets)
- CONP-<Province_name>
- Canadian-<Province_name>
- International-<Country_name>

**Comment by glatard** [comment]
Is there a reason why McGill is hardcoded instead of having a placeholder for institution as is the case for city name and province?
* CONP-<institution_name>-Institution
* Canadian-<institution_name>-Institution

**Comment by emmetaobrien** [comment]
@glatard: my understanding when this proposal was first mooted was that it might be politically significant to specifically indicate how much data was coming from institutions outside McGill, but that that was not a question that necessarily applied to other institutions.

**Comment by emmetaobrien** [comment]
Decided at the CONP dev meeting of July 22 2020 to approach this with a set of fields for institutional location instead.
