### ISSUE TITLE
Proposal: add set of fields to consistently record the institution where a dataset was generated.

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#370]
## Purpose

The object of this set of fields is to enable quick and easy querying of the complete set of datasets to determine numbers and proportions of CONP data by location (e.g. for reports to funding agencies.)

## Possible Implementation

The proposed set of fields would go under `extraProperties->origin`, and could contain:
`extraProperties->origin->institution`
`extraProperties->origin->city`
`extraProperties->origin->province`
`extraProperties->origin->country`

The first three of these fields would apply to data generated within Canada.  This also allows for cross-validation against `CONP_status`, as that field and these should be consistent.

@samirdas suggested making it required to fill in one of these values, but not necessarily all of them.  As this is going under `extraProperties` it will not be verifiable using the DATS schema anyway, so validating this would need to be carried out by external code such as @zxenia's at https://github.com/CONP-PCNO/conp-dataset/pull/363.

As `extraProperties->origin->institution` implies the city and province in which the institution is located, it would be possible to manually curate the more general fields based on the value of `institution`.

We would also need to decide on values to represent the situation where a dataset has been generated by an international consortium or other such organisation so that "institute of origin" is not meaningful.

**Comment by cmadjar** [comment]
Looks good to me!

A few thoughts: `institution` and `city` field could also be filled in for international datasets. `province` could also represent `state` for USA if needed.

Regarding consortium, maybe we could add:
`extraProperties->origin->consortium` and require either `institution` or `consortium`? And in the description of the GUI, the text could explain that this field would hold consortium or organization name that published the dataset.

Thoughts?

**Comment by emmetaobrien** [comment]
We certainly could fill in `institution` and `city` for international datasets, if we want; this structure supports that, but do we want to require it? 

I like your approach to `consortium'.

**Comment by StoneJessica** [comment]
I think if any field is required it should be the institution or consortium because we could ascertain the remaining fields from that in most cases I would think? Thanks both!

**Comment by cmadjar** [comment]
I think we have a plan then! :)

Summary of the plan:

The proposed set of fields would go under `extraProperties->origin`, and could contain:
`extraProperties->origin->institution`*
`extraProperties->origin->consortium`* (representing consortium or organization name)
`extraProperties->origin->city`
`extraProperties->origin->province`
`extraProperties->origin->country`

As `extraProperties->origin->institution` implies the city and province in which the institution is located, it would be possible to manually curate the more general fields based on the value of institution.

The required fields would be either `extraProperties->origin->institution`* or `extraProperties->origin->consortium`*. Other fields can be derived from those if they are not filled by the group creating the DATS file.

@emmetaobrien is that something you could start working on? I can help you modify some DATS file too so you do not have to do them all if you wish. Let me know.

**Comment by zxenia** [comment]
Hi @cmadjar , @emmetaobrien 
I started fixing McGill dataset for the origin description.
The below description won't pass validation under the current schema. Because `addiotionalProperties `in [category_values_pair_schema.json](https://github.com/CONP-PCNO/schema/blob/master/category_values_pair_schema.json) are not allowed.

```
{
      "category": "origin",
      "values": [
        {
          "institution": "McGill EMC",
          "city": "Montreal",
          "province": "Quebec",
          "country": "Canada"
        }
      ]
 }
```

It's only possible to add information in "value" and "valueIRI" properties.
The following will pass the validation, but we have to get rid of `origin` in this case:


```
{
      "category": "institution",
      "values": [
        {
          "value": "McGill EMC"
        }
      ]
    },
    {
      "category": "city",
      "values": [
        {
          "value": "Montreal"
        }
      ]
    },
    {
      "category": "province",
      "values": [
        {
          "value": "Quebec"
        }
      ]
    },
    {
      "category": "country",
      "values": [
        {
          "value": "Canada"
        }
      ]
 }
```

Let me know what are your thoughts about it?

**Comment by emmetaobrien** [comment]
I would favour calling those various fields `origin_institution`, `origin_country `and so on but otherwise that looks good to me.

**Comment by cmadjar** [comment]
OK. Let's go with:

```
{
      "category": "origin_institution",
      "values": [
        {
          "value": "McGill EMC"
        }
      ]
    },
    {
      "category": "origin_city",
      "values": [
        {
          "value": "Montreal"
        }
      ]
    },
    {
      "category": "origin_province",
      "values": [
        {
          "value": "Quebec"
        }
      ]
    },
    {
      "category": "origin_country",
      "values": [
        {
          "value": "Canada"
        }
      ]
 }
```

**Comment by emmetaobrien** [comment]
That looks good, and I will start updating DATS.json files for it now.

**Comment by jbpoline** [comment]
@emmetaobrien  @liamocn  Make sure this is also in the GUI

**Comment by zxenia** [comment]
@emmetaobrien @cmadjar 
As suggested in the description - make only one of these fields required: so would it be then `origin_institution` which is required field?

Should it be required only for the top-level dataset, or also for all nested children datasets in `hasPart`? I suppose it depends on how it is used in frontend if only top-level descriptions are used for stats and map on the website when we don't need this info in children datasets.

**Comment by zxenia** [comment]
based on the discussion I gathered that:
- `origin_institution ` OR  `origin_consortium ` are required for data providers

- all of the fields are required for data curators and for the validation (tests): basically, if we are provided with a dataset that has only `origin_institution `we have to add its location info before we integrate  the dataset

**Comment by emmetaobrien** [comment]
The location info will not always use a consistent set of fields, though.  For example, institutions in Canada and the US will have their province or state of origin in `origin_province`, but there is no equivalent value for an institution in the UK.  And on the other hand, `origin_consortium` can have values for city, province etc. in the case of data generated by a collaboration between multiple institutions in the same city.  I do not think we want to go to deep into complex requirements for the fields other than `origin_institution` OR `origin_consortium` , just recommend that they be filled where possible.

**Comment by emmetaobrien** [comment]
With the merging of https://github.com/CONP-PCNO/conp-dataset/pull/373, this metadata reformat has been applied to 21 dataset and all relevant `hasPart` entries:
- 1000GenomesProject
- BigBrain and the 2 derived datasets BigBrain_3DStructure and BigBrain_3DClassifiedVolumes
- Brainspan
- celltypes 
- the 3 Khanlab datasets
- mm_neo_atlas
- nhpatlas
- the 6 openpain datasets
- PreventAD-open and PreventAD-open-BIDS
- the 3 refseq datasets
- visual-working-memory

A PR has been submitted for an updated DATS.json file for the cneuromod dataset and when @glatard accepts that conp-dataset will be updated appropriately.

**Comment by emmetaobrien** [comment]
https://github.com/CONP-PCNO/conp-dataset/pull/390 updates DATS.json in the Reusing-Neuro-Data dataset with origin fields.

**Comment by emmetaobrien** [comment]
https://github.com/CONP-PCNO/conp-dataset/pull/404 updates DATS.json in cneuromod with origin fields.

**Comment by emmetaobrien** [comment]
I have updated DATS.json files for the crawler-derived datasets https://github.com/conp-bot/conp-dataset-Comparing-Perturbation-Modes-for-Evaluating-Instabilities-in-Neuroimaging-Processed-NK/, https://github.com/conp-bot/conp-dataset-Learning_Naturalistic_Structure__Processed_fMRI_dataset/ and https://github.com/conp-bot/conp-dataset-MRI_and_unbiased_averages_of_wild_muskrats__Ondatra_zibethicus__and_red_squirrels__Tami/tree/ and contacted the data providers asking them to update their Zenodo entries, and have two more ready to go when I get contact information.

**Comment by emmetaobrien** [comment]
We hit an obstacle on this in that the GUI for updating files to Zenodo raises errors with .json files; this is a known behaviour at Zenodo (https://github.com/zenodo/zenodo/issues/1453) but that does not look like it will be addressed any time soon.

After discussion at this morning's CONP dev meeting, @glatard suggested two possible approaches (copied from conversation in Slack)

 1. Require that users upload DATS files without the json extension (just DATS), and have the crawler rename the file.
 2.  For datasets uploaded as a zip, require that the DATS file be in the zip, not next to it.

Approach 1 will require some modification to the Zenodo crawler. As an experiment with approach 2, I contacted @gkiar to request that the Zenodo repository be updated accordingly, and we now have a PR for an update to https://github.com/conp-bot/conp-dataset-Comparing-Perturbation-Modes-for-Evaluating-Instabilities-in-Neuroimaging-Processed-NK/ with a tarballed DATS file which has uploaded to Zenodo and been picked up by conp-bot.

https://github.com/CONP-PCNO/conp-dataset/pull/421

**Comment by cmadjar** [comment]
I think this can be closed now. @emmetaobrien feel free to reopen if needed.
