### ISSUE TITLE
Inclusion of Zenodo, FRDR and OSF fields in the DATS model

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#375]
## Purpose

* Review the metadata fields available in Zenodo, OSF and FRDR
* Match them with our DATS model: https://github.com/CONP-PCNO/conp-dataset/tree/master/scripts/dats_validator and document the mapping in our documentation
* Update the crawlers to use these fields to populate the generated DATS models

## Context

It would make auto-generated DATS models richer

**Comment by cmadjar** [comment]
@glatard Thank you for creating the issue. I slightly modified the description to add a documentation section instead of creating a separate ticket just for the documentation. Let me know if I missed or misunderstood something.

Thank you!.

**Comment by cmadjar** [comment]
- OSF crawler PR: #478 
- OSF crawler documentation PR: https://github.com/CONP-PCNO/conp-documentation/pull/49
