### ISSUE TITLE
Tracking the FRDR crawler

### ISSUE THREAD

**Issue by gi114** [CONP-PCNO/conp-dataset#381]
## Purpose and current status
This issue is tracking the progress of the FRDR crawler

There are 2 different paths the crawler must be tested on:
1 - A new globus dataset is discovered in FRDR which must be added to CONP
2 - A globus dataset existing in CONP is found to have been moved to a different globus endpoint. The change must be reflected in CONP

Currently, path 1 is under testing, hopefully close to the end of the testing process for this path 

Updates will follow..

**Comment by cmadjar** [comment]
https://github.com/CONP-PCNO/conp-dataset/pull/401

**Comment by cmadjar** [comment]
Updates on this topic based on discussions during CONP dev meeting of November 4th, 2020:

On FRDR, there are two types of datasets:
1) Datasets with HTTP links. (easy win)
2) datasets hosted by FRDR using Globus (a little heavier, will need authentication. Kind of how we handle private Zenodo datasets?)

Start with the easy win (1) and send a PR, then move to the more complex case scenario.
