### ISSUE TITLE
CHBMP

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#382]
* Test build: 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/754/workflows/5b3eab59-7971-4100-81c8-67e4ef4d28e5/jobs/1518

* Standard error:
```
Cannot download file (dataset requires authentication, make sure that environment variables CHBMP_USERNAME, CHBMP_PASSWORD, and CHBMP_LORIS_API are defined in CircleCI).
```

* Help requested from:
@glatard @emmetaobrien 

Note: there is no data files in CHBMP as they do not have ethics yet to share their dataset. I am not sure why this particular error message is displayed since there are no files to get...

**Comment by glatard** [comment]
The test suite requires that private (or registered access) datasets define these variables even if they are not used. I did it, tests should now pass.

**Comment by glatard** [comment]
Tests seem to be passing now, feel free to re-open if there are still issues.
