### ISSUE TITLE
Braincode fBIRN -  Long-term, Phantom Quality Assurance data for functional MRI

### ISSUE THREAD

**Issue by zxenia** [CONP-PCNO/conp-dataset#388]
* Test build: 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/834/workflows/76ffc045-942e-4d57-bbde-6e725ad16168/jobs/1673

* Standard error:
`Cannot download file (dataset requires authentication, make sure that environment variables BRAINCODE_FBIRN_USERNAME, BRAINCODE_FBIRN_PASSWORD, and BRAINCODE_FBIRN_LORIS_API are defined in CircleCI).`

* Help requested from:
@glatard @emmetaobrien @joeyzhou98 

**Context:** There is no access to the actual data as it is only possible via the registered access on braincode website. The dataset contains only DATS files, readme and logo.

**Comment by cmadjar** [comment]
This is probably related to the same issue I am having for a LORIS dataset: https://github.com/CONP-PCNO/conp-dataset/issues/382

**Comment by glatard** [comment]
The test suite requires that private (or registered access) datasets define these variables even if they are not used. I did it, tests should now pass.

**Comment by glatard** [comment]
Tests seem to be passing now, feel free to re-open if there are still issues.
