### ISSUE TITLE
Braincode - Neurodevelopmental Disorders Priority Setting Partnership

### ISSUE THREAD

**Issue by zxenia** [CONP-PCNO/conp-dataset#393]
* Test build: 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/883/workflows/e996367f-ec35-46ca-8c7c-5e58c4fe3678/jobs/1772

* Standard error:
`Cannot download file (dataset requires authentication, make sure that environment variables BRAINCODE_NDD_PRIORITY_SETTING_PARTNERSHIP_USERNAME, BRAINCODE_NDD_PRIORITY_SETTING_PARTNERSHIP_PASSWORD, and BRAINCODE_NDD_PRIORITY_SETTING_PARTNERSHIP_LORIS_API are defined in CircleCI).`

* Help requested from:
The same error as #388

**Comment by glatard** [comment]
I just defined the variables, as in #388

**Comment by zxenia** [comment]
Thanks @glatard !

**Comment by glatard** [comment]
Tests seem to be passing now, feel free to re-open if there are still issues.
