### ISSUE TITLE
OSF crawled private datasets can't be downloaded by users

### ISSUE THREAD

**Issue by joeyzhou98** [CONP-PCNO/conp-dataset#408]
## Expected Behavior
 Having setup an OSF provider with the right token, see [here](https://github.com/datalad/datalad/issues/4376), using `datalad get` on an OSF private dataset that has been crawler by the OSF crawler like https://github.com/conp-bot/conp-dataset-Private-Test, we should be able to retrieve the file

## Current Behavior
Using `datalad get`, it says invalid authentication
![image](https://user-images.githubusercontent.com/35869923/91513345-19080480-e8b2-11ea-8073-e136be54b65b.png)

## Possible fix (optional)
Make sure that when you call `datalad get`, it passed by the OSF provider to use the bearer token with all its calls

**Comment by cmadjar** [comment]
@joeyzhou98 Can this be closed now that #572 has been merged?

**Comment by joeyzhou98** [comment]
Yes it can
