### ISSUE TITLE
Reusing-Neuro-Data

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#409]
* Test build: 
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/999/workflows/fada49c9-234b-43a3-9cad-663941ed875a/jobs/2008

* Standard error:
Too long to paste here (datalad install seems to be failing)

* Help requested from:
@emmetaobrien

**Comment by emmetaobrien** [comment]
Fixed by https://github.com/CONP-PCNO/conp-dataset/pull/412.
