### ISSUE TITLE
New dataset: Multi-model functionalization of disease-associated PTEN missense mutations

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#415]
This issue is to track progress on importing https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/DQOKPB, suggested by Dr. Paul Pavlidis as a suitable candidate for import to CONP from among the data generated by his group.

**Comment by emmetaobrien** [comment]
The contents of this dataset have been uploaded to the repository https://github.com/emmetaobrien/Multi-model_functionalization_of_disease-associated_PTEN_missense_mutations.

**Comment by cmadjar** [comment]
@emmetaobrien I added the in-progress label but I have feeling this is done, no? I can see the dataset on the portal. Maybe there are some edits to be added that I forget?

If done, I will let you the pleasure to close the issue ;).

**Comment by emmetaobrien** [comment]
The dataset is in the portal; I am still waiting to possibly hear back on a logo and an updated landing page, but neither of those impair functionality.
