### ISSUE TITLE
New dataset: Systematic phenomics analysis of autism-associated genes 

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-dataset#416]
This issue is to track progress on importing https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/FJWIL8 suggested by Dr. Paul Pavlidis as a suitable candidate for import to CONP from among the data generated by his group.

**Comment by emmetaobrien** [comment]
The contents of this dataset have been uploaded to the repository https://github.com/emmetaobrien/Systematic_phenomics_analysis_of_autism-associated_genes.

**Comment by cmadjar** [comment]
@emmetaobrien I added the in-progress label but I have feeling this is done, no? I can see the dataset on the portal. Maybe there are some edits to be added that I forget?

If done, I will let you the pleasure to close the issue ;).

**Comment by emmetaobrien** [comment]
This dataset is also functional in the portal, but may be updated for a logo and a landing page.
