### ISSUE TITLE
MouseBytes Dataset

### ISSUE THREAD

**Issue by paiva** [CONP-PCNO/conp-dataset#42]
It would be a good idea to try to get the MouseBytes dataset presented at the CONP Plenary meeting on the CONP Portal

**Comment by jbpoline** [comment]
Agreed - do you have the contacts for that ? I can dig this out if not.

**Comment by jbpoline** [comment]
update: Ali is hiring an open science developer who could do some work on this

**Comment by tkkuehn** [comment]
I've been in touch with the MouseBytes team now, and am working on scheduling a meeting with them and a few other CONP developres to discuss the best way to push this forward.

The MouseBytes data is all behavioural for now and is stored in an SQL database, which they expose to queries with a [web page](https://mousebytes.ca/data-extraction), from which subsets of the data can be exported in .csv format.

They don't yet have any public API that exposes the data, but are open to developing something to facilitate exposing the data on the Portal. I think they envision some mechanism for searching the dataset within the Portal, but they could expose .csv files containing the data if that's the only feasible option.

**Comment by tkkuehn** [comment]
We all met today - here's my understanding of the approach we'll take.

In the very short term, we'll start by indexing MouseBytes on the CONP Portal with a DATS model including a link to the MouseBytes Data Lab. @emmetaobrien will send the MouseBytes team the DATS editor, so they can use it and provide some feedback on the GUI. The goal is to have MouseBytes on the portal in this form by our next meeting in two weeks.

In the slightly longer term, we'll start sharing data by executing the most useful queries on the MouseBytes database on a regular basis, and exposing the results as .csv files on the CONP Portal to make them easy to access from the Portal. The MouseBytes team will discuss what these most useful queries are, and prepare a list for our next meeting in two weeks.

In the long term, we'd like to expose MouseBytes (and other datasets) to queries from CONP, allowing MouseBytes data to be aggregated with other relevant datasets. Once we've shared MouseBytes in the form described above, we can start planning for this project.

**Comment by cmadjar** [comment]
@tkkuehn Can this be closed?

**Comment by tkkuehn** [comment]
Yes, MouseBytes is on the CONP Portal, so we can close this issue.
