### ISSUE TITLE
OSF crawler chocking on datasets with multiple data providers

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#430]
Up until now, the datasets we got from OSF only stored data in one data provider (`OSF Storage`). 

However, there is now a dataset that has two data providers set (`OSF Storage` and `Github`): https://osf.io/k5zb9/

Currently, in the script, it is hardcoded to take the first data provider in the JSON response of the OSF API and import the files from there. Unfortunately, in the case of the new dataset, there is more than one data provider, and the first one is the Github one. Since the properties of the API response of the `Github` data provider are different than the ones from the `OSF Storage` data provider, the crawler chokes with the following error:

```bash
OSF query: https://api.osf.io/v2/nodes/?filter[tags]=canadian-open-neuroscience-platform
Traceback (most recent call last):
  File "scripts/crawl.py", line 75, in <module>
    OSFCrawler.run()
  File "/Users/cmadjar/conp-dataset/scripts/Crawlers/BaseCrawler.py", line 228, in run
    dataset_description_list = self.get_all_dataset_description()
  File "/Users/cmadjar/conp-dataset/scripts/Crawlers/OSFCrawler.py", line 141, in get_all_dataset_description
    root_folder_link = self._get_request_with_bearer_token(
KeyError: 'root_folder'
```

#### Option 1:

Instead of only crawling `OSF Storage` files, we could crawl all types of data providers. 

**Implications:**
- a bit complex to handle for the already crawled dataset - not sure how to update them
- the organization of the new datasets would then differ from the datasets already crawled - not sure how that would behave if a dataset is updated...

**To illustrate the data structure changes:**
1) current structure
```bash
__ conp-dataset-Multimodal-data-with-wide-field-GCaMP-imaging
    |__ .datalad/
    |__ Part_1/
    |__ Part_2/
    |__ .conp-osf-crawler.json
    |__ .gitattributes
    |__ DATS.json
    |__ README.md
```
2) proposed structure (replicating OSF's structure)
```bash
__ conp-dataset-Multimodal-data-with-wide-field-GCaMP-imaging
    |__ .datalad/
    |__ osfstorage/
         |__ Part_1/
         |__ Part_2/
    |__ .conp-osf-crawler.json
    |__ .gitattributes
    |__ DATS.json
    |__ README.md
```

#### Option 2:

Ignore files that are not under the `osfstorage` data provider (meaning looping over the different data providers and skip them until we get to the `osfstorage` data provider). 

**Implications:**
- would be missing files in the CONP datasets copied from OSF
- easier to manage with the current crawler as this would not change the structure of the current datasets

#### Option 3: 

Loop through all data providers:
- if the data provider is not `osfstorage`, then create a directory with the data provider name where all the files from that data provider would be linked (for example `github/`)
- if the data provider is `osfstorage`, then do not create a root folder `osfstorage`, instead crawl the files directly in the root directory of the dataset

Implications:
- easier to manage already crawled datasets
- might back fire on us if at some point a folder in `osfstorage` has the same name as an additional data provider. For example: there is a `github` folder in the data present in `osfstorage` and a `github` data provider which would end up in the creation of a `github` fodler at the same place than the folder created for the `osfstorage`...

## Related issues (optional)

This is blocking the following issues: 
- https://github.com/CONP-PCNO/conp-dataset/issues/417
- https://github.com/CONP-PCNO/conp-dataset/issues/418 (when they updated their DATS.json and README files)

**Comment by glatard** [comment]
Hi @cmadjar, very good catch and thanks for the thorough issue report. I am in favour of option 1 because:
* Option 3 may lead to conflicting file names if the dataset has more than 1 osf storage (your 'backfire' comment I guess)
* Option 2 may lead to incomplete datasets.

It would also be worth checking how the modified crawler behaves on https://osf.io/xhvsk (related to #405 and #406)
