### ISSUE TITLE
Khanlab/HCPUR100-Template 

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-dataset#431]
I am trying to download Khanlab/HCPUR100-Template/blob/master/sub-HCPUR100/anat/sub-HCPUR100_t1w.nii.gz but I only get a text file with `/annex/objects/MD5E-s11057707--6248ded9a528636072aba8b4ec857dfb.nii.gz`

* Test build: 
 I am not sure what to put here.

**Comment by emmetaobrien** [comment]
It looks like the source dataset was re-initialised in May with the intent of updating the links and instead replaced them with text files, I shall contact Jason Kai about this.

**Comment by emmetaobrien** [comment]
This should be fixed by https://github.com/CONP-PCNO/conp-dataset/pull/433.

**Comment by xlecours** [comment]
fixed
