### ISSUE TITLE
[validator] check that a DataLad subdataset exists when DerivedFrom is filled in DATS.json

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#436]
## Purpose

A derived dataset should always have the dataset it is derived from as a DataLad subdataset. Below is the example of how derived datasets should be organized (example of preventad-open-bids).

- DATS.json content for DerivedFrom example
```
    {
      "category": "derivedFrom",
	  "values": [
        {
          "value": "https://github.com/conpdatasets/preventad-open/tree/17dd9742a89e60f720f8276d79d917c54dd20695"
        }
      ]
    },
```

- Directory structure of a derived dataset (example of preventad-open-bids):
```
.datalad/
BIDS_dataset/
preventad-open @ 17dd974/
.gitattributes
.gitmodules
DATS.json
README.md
logo.png
```

=> add a check that verifies that the DataLad subdataset is indeed present and on the correct commit (based on the value in the DATS.json file)

**Comment by zxenia** [comment]
@cmadjar 
In the example, `derivedFrom` points to a specific version of preventad-open dataset: `https://github.com/conpdatasets/preventad-open/tree/17dd9742a89e60f720f8276d79d917c54dd20695` (from Aug 11)
But currently, there is a newer version of preventad-open dataset (From Oct 13). Is this a desired behavior, to have a specific version in the tree here?
Does this mean that this dataset https://github.com/conpdatasets/preventad-open-bids is not derivedFrom from the latest version https://github.com/conpdatasets/preventad-open ?

**Comment by cmadjar** [comment]
@zxenia I think the only file that changed between the two commits is the DATS file to add the Zenodo DOI. All the data files are identical. 

I guess I need to send a PR to update the preventad-open dataset in the preventad-open-bids dataset. Unless there is a better way to do that?

**Comment by zxenia** [comment]
Then would it be a solution to point to a dataset repo in `derivedFrom` but not to its version in a tree?
for example:

```
{
      "category": "derivedFrom",
	  "values": [
        {
          "value": "https://github.com/conpdatasets/preventad-open"
        }
      ]
 }
```

**Comment by cmadjar** [comment]
that seems reasonable to me. @emmetaobrien do you agree? If so, I will send a PR to fix that shortly :).

**Comment by emmetaobrien** [comment]
This entirely makes sense to me.
