### ISSUE TITLE
Harmonized values for our DATS datasets descriptors

### ISSUE THREAD

**Issue by jbpoline** [CONP-PCNO/conp-dataset#454]
## Purpose
Suggest some harmonized values for the DATS model in the GUI, 

## Context
This would help find datasets with a specific values, make sure that these values are linked to a place with a definition, propose default values in the GUI

## Possible Implementation (optional)
Create a first json/md text files with most used / most recommended values

## List of fields to be harmonized:

- [x] units
- [x] file format #491 
- [x] date types #499 
- [x] privacy #532 
- [x] licenses #541
- [x] isAbout #533
- [x] keywords #543
- [x] data types #542
- [ ] dimensions

**Comment by cmadjar** [comment]
@liamocn @PapillonMcGill could you discuss what the best format would be?

My guess would be the following:
- create a JSON file that could be parsed by the GUI to provide pre-established values for the fields
- would be nice for the fields to hint to the users what to enter when they start typing in the words

Thoughts? 

Thank you :)

**Comment by cmadjar** [comment]
For the DataType, we could provide a list of terms from the interlex URI dashboard (https://neuinfo.org/interlex/dashboard). Is that the only source of terms to use there?

Suggestion to build list of terms on top of the NIDM-terms group. To be discussed today at the CONP dev.

**Comment by PapillonMcGill** [comment]
No Interlex is not the only one. It is one if not the most comprehensive list of term for medical research. Easy to had new one if yours term is not there or definition do not mach perfectly your need.
