### ISSUE TITLE
Combine Dataset ID with OpenID? 

### ISSUE THREAD

**Issue by paiva** [CONP-PCNO/conp-dataset#46]
Is there a way we could combine the id of a dataset (or subdataset) with the OpenID that @johnsaigle is working on?

**Comment by johnsaigle** [comment]
The Open Science Identifier is completely standalone:
https://github.com/aces/open_science_identity

There are examples there in many languages. You can easily generate them and store them in your application.

When it comes time to link data between your tool and LORIS (or others), they can be joined using the ID.
