### ISSUE TITLE
mm_neo_atlas

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#481]
It looks like none of the files of this dataset can be downloaded.

One example from a Circle CI failed run:
```
projects/mm_neo_atlas/lc_probs.zip
download failed: Not Found
download failed: Not Found
download failed: Not Found
```

Tried running `datalad get`  on all the files and none appears to be downloadable unfortunately. Part of the error:
```
[ERROR  ] from web...; Unable to access these remotes: web; Try making some of these repositories available:;   00000000-0000-0000-0000-000000000001 -- web; ; (Note that these git remotes have annex-ignore set: origin) [get(/data-scratch1/for_CONP_portal/conp-dataset/projects/mm_neo_atlas/lc.F.bam.bai)]
get(error): lc.F.bam.bai (file) [from web...; Unable to access these remotes: web; Try making some of these repositories available:;    00000000-0000-0000-0000-000000000001 -- web; ; (Note that these git remotes have annex-ignore set: origin)]
action summary:
  get (error: 47, notneeded: 5)
```

**Comment by emmetaobrien** [comment]
The source server appears to be down, it's not clear whether this is permanent; I will check in again over the next while, and remove the dataset from the CONP interface if this persists.

**Comment by cmadjar** [comment]
Thank you @emmetaobrien I was afraid it would be something like that. Hopefully the server gets back online soon.

**Comment by emmetaobrien** [comment]
The mm_neo_atlas dataset continues non-functional and has been removed for the moment.
