### ISSUE TITLE
Harmonization of the DATS.json formats field

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#491]
## Purpose

At the moment, file formats stored in the DATS.json files of the dataset are not very harmonized (for example, .mnc and MINC refers to the same file format, txt, .txt and TXT etc...).

Need to harmonize values across datasets so they can be properly represented in the portal. Will also need to modify the DATS GUI to enforce the harmonization.

Proposed convention: by default, all file formats will be upper case without dots unless the format specifically requires particular casing (such as bigWig and NIfTI).

**Initial list of file format based on what is already present in the datasets:**
- BAM
- BIDS
- bigWig
- CEL
- CSV
- DICOM
- EEG-BIDS
- FASTA
- FASTQ
- GIF
- GFF
- GTF
- GZIP
- H5
- JPEG
- JSON
- MIF
- MINC
- MRI-BIDS
- NIfTI
- PDF
- RNA-Seq
- STL
- TSV
- TXT
- VCF
- XLS
- ZIP

In this list, there are only 3 formats that do not follow the upper case convention:
- NIfTI
- BigWig
- RNA-Seq

## Context

This is one subtask related to https://github.com/CONP-PCNO/conp-dataset/issues/454

## Possible Implementation

- [x] convert format in the existing DATS files to comply with convention above for non-crawled dataset
  - [x] nhpatlas https://github.com/CONP-PCNO/conp-dataset/pull/490
  - [x] Brainspan https://github.com/CONP-PCNO/conp-dataset/pull/490
  - [x] refseq Callithrix https://github.com/CONP-PCNO/conp-dataset/pull/490
  - [x] refseq Homo https://github.com/CONP-PCNO/conp-dataset/pull/490
  - [x] refseq Mus https://github.com/CONP-PCNO/conp-dataset/pull/490
  - [x] Khanlab/HCPUR100-Template https://github.com/CONP-PCNO/conp-dataset/pull/492
  - [x] Khanlab/BigBrainHippoUnfold https://github.com/CONP-PCNO/conp-dataset/pull/492
  - [x] 1000 genomes project https://github.com/CONP-PCNO/conp-dataset/pull/490
  - [x] multi-model functionalization of disease-associated PTEN missense mutations https://github.com/CONP-PCNO/conp-dataset/pull/490
  - [x] systemic phenomics analysis of autism-associated genes https://github.com/CONP-PCNO/conp-dataset/pull/490
  - [x] mcgill EMC: RNA-seq dataset https://github.com/CONP-PCNO/conp-dataset/pull/497
- [x] rerun the crawler on the datasets that are failing the format convention above
  - [x] VFA T1 mapping RTHawk open vs Siemens commercial https://github.com/CONP-PCNO/conp-dataset/pull/493
  - [x] Learning naturalistic structure processed fMRI dataset (**need to contact the owner of the dataset to change the DATS file**)
  - [x] MRI and unbiased averages of wild muskrats Ondatra zibethicus and red squirrels Tamiasciurus hudsonicus https://github.com/CONP-PCNO/conp-dataset/pull/496
- [ ] modify the DATS GUI editor to automatically save file format in upper case while handling the 3 exceptions above https://github.com/CONP-PCNO/conp-dats-editor/issues/14
- [x] modify the validator script to enforce the convention https://github.com/CONP-PCNO/conp-dataset/pull/498
- [x] modify the portal code to display formats as upper case except for the three exceptions above https://github.com/CONP-PCNO/conp-portal/pull/394

## Related issues (optional)

https://github.com/CONP-PCNO/conp-dataset/issues/454

**Comment by emmetaobrien** [comment]
I have updated the two Khanlab datasets accordingly and submitted PRs to the source repositories.

**Comment by cmadjar** [comment]
The only part missing to close that ticket is the update to the DATS GUI. An issue has been created in the DATS editor GUI. Will reference that issue in the winter project and close this one as everything else was completed.
