### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#51]
We should create a template for pull requests, containing a check list of required properties for the new dataset. A good start for the template is the one now in use for conp-portal (see [here](https://github.com/CONP-PCNO/conp-portal/blob/master/.github/PULL_REQUEST_TEMPLATE.md)). The checklist should contain the items being implemented in continuous integration: https://github.com/CONP-PCNO/conp-dataset/issues/16 It should also contain an item checking that every new release of the dataset will have a DOI created through Zenodo, with a [link](https://guides.github.com/activities/citable-code/) to GitHub's documentation on how to enable that.

**Comment by jbpoline** [comment]
Agreed. @paiva @PapillonMcGill can you take that on board ?

**Comment by PapillonMcGill** [comment]
@jbpoline Yes, we can definitively. It should also contain a link to the list of metadata fields and their priority (Required, Recommended, Optional,...) when ready

**Comment by glatard** [comment]
A good part of it is in #50. @jbpoline, would you like to review it?
