### ISSUE TITLE
List of datasets that are missing subjects value in extra property

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#515]
The following datasets are missing the subjects extra property value in their DATS.json files as flagged by #507:
- [ ] Multi-model_functionalization_of_disease-associated_PTEN_missense_mutations (waiting to hear back from Paul Pavlidis)
- [x] nhpatlas
- [ ] all openpain datasets (waiting to hear back from the openpain people for the number of subjects for their datasets)
- [ ] Systematic_phenomics_analysis_of_autism-associated_genes (waiting to hear back from Paul Pavlidis)

**Comment by cmadjar** [comment]
@emmetaobrien the list above are what still needs to have the subjects extra property added to the dataset. I remember you contacted the openpain people and are still waiting for their answers.

Did you also contact the owners of nhpatlas, Multi-model_functionalization_of_disease-associated_PTEN_missense_mutations and Systematic_phenomics_analysis_of_autism-associated_genes? I don't remember.

Thanks!

**Comment by emmetaobrien** [comment]
I have found the documentation for `nhpatlas` and updated that now.

**Comment by emmetaobrien** [comment]
And I have mailed Paul Pavlidis to inquire after the subject counts for the other two datasets.

**Comment by emmetaobrien** [comment]
Addressed in https://github.com/CONP-PCNO/conp-dataset/pull/516
