### ISSUE TITLE
Submit CONP terms to NIDM

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#535]
Following our earlier discussion today, here is the list of modification that needs to occur before submission to NIDM of the CONP terms. @zxenia feel free to add anything I might have missed.

### privacy field:

Terms should be one of:
- open (same as public)
- registered 
- controlled (same as restricted)
- private (same as controlled)

### isAbout

Terms that are not species to be added:
- adult
- older adult
- healthy
- total RNA
- Alzheimer's disease

### data types

Terms to add:
- imaging
- QA summary results
- normative database (maybe?)

**Comment by cmadjar** [comment]
@zxenia for the licenses terms, I just noticed that in the DATS GUI, we have all of those:
- CC BY
- CC BY-SA
- CC BY-NC
- CC BY-NC-SA
- CC BY-ND
- CC BY-NC-ND
- CC0
- ODbL
- ODC-By
- PDDL

Might be worse representing all of them in your future NIDM PR. Thoughts?

**Comment by zxenia** [comment]
@cmadjar Thanks Cécile! Yes, I think it makes sense since these are our suggested values. I will add those licenses to the terms too.

**Comment by cmadjar** [comment]
Should this be closed?

**Comment by zxenia** [comment]
@cmadjar Hi, yes this can be closed, the terms are submitted and accessible at the NIDM terminology website.
