### ISSUE TITLE
Identify which license value should be used as a default by the DATS GUI when a user does not specify a license

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#539]
For the DATS GUI, if a user does not specify a license the DATS GUI should then specify a default license and prompt the user by telling the user what the default license will be attached in their DATS file.

Need to figure out which default license to use.

**Comment by cmadjar** [comment]
@emmetaobrien maybe you could look into which default license could be used for the DATS GUI? Thank you!

**Comment by cmadjar** [comment]
I added the discussion required as this will probably need to be validated at the CONP dev meeting which license should be the default license and whether it should also be added to the crawlers.

**Comment by cmadjar** [comment]
@emmetaobrien Have you had a chance to look into this? Thanks!

**Comment by emmetaobrien** [comment]
I have added this to the agenda for next week's dev meeting.

**Comment by cmadjar** [comment]
@emmetaobrien could you update the issue with what has been discussed?

**Comment by cmadjar** [comment]
@emmetaobrien any updates on this? If so, could you update the issue please? Thanks!

**Comment by emmetaobrien** [comment]
Current status here is as follows:

If a license has not been specified in the license field, in a Zenodo or OSF entry, it is most likely mentioned in the README.  Therefore we search the README file for a recognisable license specification (e.g. CC BY-SA) and populate our license field with it if we find one.

**Comment by cmadjar** [comment]
Ok. Thank you for the update! Should this be closed then?

**Comment by emmetaobrien** [comment]
While this method appears to work, I don't think we can guarantee that it will cover every possible option we might encounter; happy to close it for the moment until we find an exception, though.
