### ISSUE TITLE
Add a license to this repository

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#54]
## Purpose
Add a license to this repository.

## Context
The [GitHub community guidelines](https://github.com/CONP-PCNO/conp-dataset/community) recommend to adopt a clear license for any community-driven project. We need to clarify that. This license would cover the actual content of this repo, i.e., the metadata and any other file (test files, etc). The data itself wouldn't be covered, as it is not part of the repo.

## Possible Implementation

It sounds reasonable to have a very permissive license to avoid further issues, as the real value of this repository is the data. Two options seem reasonable:
1. [MIT license](https://en.wikipedia.org/wiki/MIT_License)
2. [CC Zero](https://creativecommons.org/choose/zero)
I'm not sure how MIT license applies to data, and I'm not sure how CC Zero applies to software. For instance, CC Zero isn't in the license templates provided by GitHub. 

This needs to be discussed. Maybe the ethics group could chime in too (does anyone know their GitHub handle?).

@shots47s @jbpoline @akhanf @edickie

**Comment by shots47s** [comment]
So this would be a license to the software in the repository or for the data? This is interesting, because we don't necessarily hold the license on the data, so really each dataset should specify what their licensing is.  Our should be a license on the "metadata" and other accoutrement around it.  Right?

**Comment by dlq** [comment]
While GitHub "recognizes" mainly open source software licenses:

https://help.github.com/en/articles/licensing-a-repository#searching-github-by-license-type

You can put whatever the original license for the data is in `LICENSE.txt`. 

But, hmm, yeah, the license text that's in the GitHub repository I guess could be about the metadata in that repository but the license text that's in the data directory - wherever it's hosted - could be about the original data.  We're not relicensing it.  Right?

**Comment by glatard** [comment]
Indeed, as explained in the issue, the license would *not* cover the data. It would only cover what's in the repo, i.e., metadata and other secondary files that might get in there.

**Comment by shots47s** [comment]
Then my vote is MIT, unrestrictive as can be.

Shawn T. Brown, Associate Director of Research Software Development, McGill
Centre for Integrated Neuroscience
