### ISSUE TITLE
Fix wrong terms used in licenses field of the current DATS files

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#540]
The following identified values need to be changed in the DATS files:
- [x] CC-By Attribution 4.0 International => `CC BY-4.0`
- [x] Creative Commons Attribution 4.0 International (CC-BY 4.0)  => `CC BY-4.0`
- [x] CC-BY-4.0  => `CC BY-4.0`
- [x] BY-NC-SA => `CC BY-NC-SA`
- [x] Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License => `CC BY-NC-SA`

**Comment by PapillonMcGill** [comment]
4.0 (version) should go to the "version" tag
i.e.: 
"name":"CC BY",
"version":"4.0"

**Comment by cmadjar** [comment]
oh, good catch! @zxenia, @emmetaobrien  I believe this will affect the NIDM term, no?

**Comment by zxenia** [comment]
I'd still keep 4.0 in the name since it's the full name of the license here https://creativecommons.org/licenses/by/4.0/

**Comment by cmadjar** [comment]
@PapillonMcGill @emmetaobrien I still see the following in the DATS files:

- `CC-By Attribution 4.0 International` should be replaced by `CC BY-4.0` for the following datasets
  - BigBrainHippoUnfold
  - Calgary_Preschool_MRI_Dataset
  - BigBrainMRICoreg
-  `Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License` should be replaced by `CC BY-NC-SA` for the following datasets:
  - BigBrain
  - BigBrain_3DSurfaces
  - BigBrain_3DClassifiedVolumes
