### ISSUE TITLE
Invalid GitHub secrets for Docker worflow.

### ISSUE THREAD

**Issue by mathdugre** [CONP-PCNO/conp-dataset#548]
The Docker build workflow fails at the authentication step.
We might want to validate the current GitHub secrets for:

- [ ] DOCKERHUB_USERNAME
- [ ] DOCKERHUB_PASSWORD

## Related issues (optional)
Initial PR #528

**Comment by cmadjar** [comment]
@mathdugre I don't think I have the login information that should be used for those secrets...

**Comment by glatard** [comment]
Updated the secrets

**Comment by mathdugre** [comment]
The Docker workflow is passing now. Closing this issue.
