### ISSUE TITLE
Improvements to the contribution guide

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#57]
## Purpose

- (A) Intended audience for the document, and what is there experience?
  - Maybe move the suggestion about reading GitHub documentation prior to the workflow heading (since there appears to be an underlying assumption of knowing how to use git. 
  - Where should a user go / who to contact if there is an issue - post under issues in the repo? Would have a help or contact section near the top for the above notes
- (B) Instructions for "Adding Data"
  - There seems to be a few different instructions regarding adding a sub-module in different documentations. Again, this could be due to the underlying assumption of git. Had some issues when I was originally setting up the sub-module for the Khanlab datasets. Think it would be good if the documents had the same instructions for the sub-modules.
  - Is there documentation available from potentially different sources (eg. aws, osf, etc.) that be linked to? Depending on the target audience, maybe there should be a note that the files need to be hosted somewhere (unless there is available space for this). 
- (C) Current instructions can also appear to imply a binary workflow - either it is already hosted somewhere (https) or to host through Google Drive, which can be potentially problematic. Suggestion would be to link to a folder of documentations that help walk the user in adding their data using their source. This does not need to be how to host the files, but just how to add from the source (eg. aws, osf, etc.) Additionally, this might help to provide some clearer instructions for users to contribute their dataset.

## Context
Suggestions made by @kaitj in #56

## Related issues (optional)
#56

**Comment by glatard** [comment]
Hi @kaitj, thanks for all the suggestions. Quick question for now: what do you mean by "in different documentations"? Are you referring to other CONP documentations? If yes, we should definitely harmonize all that.

**Comment by glatard** [comment]
(A) should be fixed in #58, feel free to chime in @kaitj

**Comment by kaitj** [comment]
> Hi @kaitj, thanks for all the suggestions. Quick question for now: what do you mean by "in different documentations"? Are you referring to other CONP documentations? If yes, we should definitely harmonize all that.

Yep, in other CONP documentations. Would be great if is harmonized.

> (A) should be fixed in #58, feel free to chime in @kaitj

Looks good!

**Comment by glatard** [comment]
Could you point me to that other CONP documentation you are referring to?

**Comment by kaitj** [comment]
If I recall, it was primarily:
* Prevoius version of the README (I think most of this is in the Contributing document now)
* [adding_datalad_datasets_workflow.md](https://github.com/CONP-PCNO/conp-documentation/blob/master/Datalad/adding_datalad_datasets_workflow.md)

The confusion at the time was mostly working with the submodules in the dataset (eg. using the `git submodule add` command to add the dataset vs the "updating the .gitmodules" file from the Contributing document).
