### ISSUE TITLE
Explore automatic linting and crawling of associated submodules separate from continuous integration.

### ISSUE THREAD

**Issue by dlq** [CONP-PCNO/conp-dataset#59]
## Purpose

Explore and define the validation rules for a project independant of a continuous integration process so that they can be run separately before committing a new submodule or apply to an existing repositories.
 
## Context

How can we automatically check the structure and contents and of a (potential) repository for use by the data hub?

## Possible Implementation

Maybe we can adapt something like [RepoLinter](https://github.com/todogroup/repolinter) somehow for our use.  This could be run at anytime by prospective contributors to understand what work they have to do to adapt their repositories for use by us.

Maybe we can crawl all associated data repositories with something like [GHCrawler](https://github.com/microsoft/ghcrawler) to run the linter automatically on these.  How this would differ from requiring a continuous integration hook - I'm not sure.

**Comment by glatard** [comment]
Hi @dlq, the tests executed by the CI process will be available through pytest and could be run locally. Do you think it would address this issue?

**Comment by dlq** [comment]
That could work.  I'm just trying to think how these tests could be run by someone preparing a data repository.

**Comment by glatard** [comment]
They could just run `pytest` in the base directory.

**Comment by dlq** [comment]
In which base directory?  In the base directory of their forked conp-datasets repository?  Or of their particular data submodule repository?

The first option will potentially have to check a lot of submodules. How?  How fast?

In the second option, where do the tests come from?

**Comment by glatard** [comment]
in the base directory of their forked conp-datasets repository. We could have options to skip tests for all datasets but the one they are interested in. @joeyzhou98 could investigate that if it makes sense.

**Comment by dlq** [comment]
Ok. That makes sense. 

Based on his feedback I’ll mark this as closed

**Comment by dlq** [comment]
This seems to belong in existing continuous integration efforts.
