### ISSUE TITLE
Go through the datasets pages and list the datasets that could use some improvements in their descriptions

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#595]
## Purpose

This has been discussed on 2021-04-23 during a meeting with Rachel, Patrick, Derek, Samir and Cécile.

Some of the datasets have limited descriptions and would need some improvements of the information provided in the DATS.json and README.md files.

**TODOs**
- create a list of the datasets that require improvements and what improvements those should be.
- contact the people that uploaded the datasets to ask them to provide more descriptive information

## Related issues 
#594

**Comment by cmadjar** [comment]
https://github.com/CONP-PCNO/conp-dataset/issues/625 contains the list of datasets automatically crawled that should probably be updated.

**Comment by cmadjar** [comment]
Removed the stale as it is still in progress with the communication committee

**Comment by emmetaobrien** [comment]
There are three pending datasets to which this issue is known to apply, all of which are on @GHPBZ's radar, so I do not think we need to keep this issue alive, the concern for older dataset consistency has been addressed.
