### ISSUE TITLE
PERFORM_Dataset__one_control_subject

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#601]
* Test build:
https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/3022/workflows/d5de4ec4-d4ee-4858-888d-95f20a830fc4/jobs/6092

* Standard error:

![Screen Shot 2021-04-29 at 9 03 03 AM](https://user-images.githubusercontent.com/1402456/116554911-be53fc00-a8c9-11eb-8cc6-7d08d5bf3b25.png)

This error has been consistant in the past few Circle CIs ran automatically to test `conp-dataset`

* Help requested from:

@mathdugre @glatard

**Comment by mathdugre** [comment]
@cmadjar , I uploaded a updated version of the dataset on Zenodo. It should be crawled shortly.

**Comment by cmadjar** [comment]
@mathdugre @joeyzhou98 tests on the PERFORM dataset are still failing. Below is the latest log from https://app.circleci.com/pipelines/github/CONP-PCNO/conp-dataset/3395/workflows/9fc2254f-9b16-4aba-be75-73d1553da00a/jobs/6833:

```
projects/PERFORM_Dataset__one_control_subject/candidates/913174/V1/instruments/913174_V1_Sleep_Diary
external special remote protocol error, unexpectedly received "[INFO] http session: Authenticating into session for https://zenodo.org/api/files/0c9e24a9-e504-4546-9a23-62b6dbfae5c3/data.zip " (unable to parse command)
unable to use special remote due to protocol error
external special remote protocol error, unexpectedly received "[INFO] http session: Authenticating into session for https://zenodo.org/api/files/0c9e24a9-e504-4546-9a23-62b6dbfae5c3/data.zip " (unable to parse command)
unable to use special remote due to protocol error
external special remote protocol error, unexpectedly received "[INFO] http session: Authenticating into session for https://zenodo.org/api/files/0c9e24a9-e504-4546-9a23-62b6dbfae5c3/data.zip " (unable to parse command)
unable to use special remote due to protocol error
```

I did set the `DATALAD_ZENODO_token` environment with a valid token in Circle CI. Would you guys have time to look into this? Thank you :)

**Comment by joeyzhou98** [comment]
I think the test isn't expecting INFO logs from Datalad, but @mathdugre could tell you more

**Comment by mathdugre** [comment]
@cmadjar, after merging #665, PERFORM passes the test. I think this issue can be closed.

**Comment by cmadjar** [comment]
Indeed. Thank you @mathdugre :)
