### ISSUE TITLE
Add definitions for the CONP terms

### ISSUE THREAD

**Issue by zxenia** [CONP-PCNO/conp-dataset#620]
## Purpose
Several terms that used in metadata and that we plan to submit to the NIDM don't have any external resources to link to or a proper definition to link to (e.g. ontology concept ID).

The terms are the following:
**Keywords:**
functional variomics
mesoscale folding
MP2RAGE
SA2RAGE

**Data types:**
high-throughput expression neuroscience data
neurosensory assessments
respondent demographics	

We need to create/add definitions for these terms.

## Context
This work is related to the submission of the CONP terms to the NIDM.

**Comment by zxenia** [comment]
The formats definitions were submitted today.
A subset of terms is still missing definitions.

**Comment by cmadjar** [comment]
@zxenia any updates on this? Thanks!

**Comment by zxenia** [comment]
@cmadjar There is no updates since the middle of October when the latest batch of terms was submitted and merged to NIDM terms. Some terms are still missing descriptions and frankly, I don't know how to go about it, maybe we can stale this issue for now and move forward with integrating the existing ones (term, link, description) to the DATS editor. What do you think?
