### ISSUE TITLE
decide on a minimum set of "isAbout" annotations required to validate

### ISSUE THREAD

**Issue by surchs** [CONP-PCNO/conp-dataset#658]
At the moment, the DATS dataset schema does not require any `isAbout` annotation - the place where we add concept level information. We will likely make `isAbout` mandatory on the DATS schema level for CONP (see https://github.com/CONP-PCNO/schema/issues/7).

That brings up the question of what (if any) information should be included in the now mandatory `isAbout` field. Some ideas during our discussion have been

- disease status (healthy, diagnosis ...)
- age
- sex

All of these are likely going to be following the [DATS taxonomic_info schema](https://github.com/CONP-PCNO/schema/blob/master/taxonomic_info_schema.json). Based on this discussion, we would probably want to make our dats-validator check that these types of information are present for a dataset to validate.

@zxenia @emmetaobrien @cmadjar @samirdas @jbpoline

**Comment by emmetaobrien** [comment]
For completeness' sake, while it is already being checked, it is probably
worth noting taxonomic information as an entity we are keeping in the
isAbout field already.  Also, I think we should come up with a standard
"dummy" value to use here in cases such as phantom data.

                             Emmet

**Comment by emmetaobrien** [comment]
Sorry, I should put that on the issue instead of mailing it. Brain melting
here.

                                     Emmet

**Comment by surchs** [comment]
Thanks @emmetaobrien, I hadn't seen [the `isAbout` check in the DATS validator](https://github.com/CONP-PCNO/conp-dataset/blob/master/scripts/dats_validator/validator.py#L243) yet. So I think then the question would become: do we want to add other constraints to this validator function and if so, for what types of annotations?

**Comment by cmadjar** [comment]
Removed stale. This is on the roadmap for November. @surchs is this assigned to you? I don't remember...

**Comment by cmadjar** [comment]
@surchs should we discuss this issue at the next CONP dev call? Thanks!

**Comment by surchs** [comment]
Hi @cmadjar, sorry, just seen. We can discuss this but I think this issue is addressed by https://github.com/CONP-PCNO/conp-dataset/pull/711. The validator is now checking for at least one taxonomy entry, correct?

**Comment by cmadjar** [comment]
@surchs That is correct. Closing the issue then. Feel free to reopen if you think there are still things to do on this.
