### ISSUE TITLE
Create multi-part archive for very large open datasets

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#659]
## Purpose

Discussed at the CONP dev of June 9th, 2021.

Figure out how to create multi-part archive for very large open datasets and investigate whether `datalad export-archives` supports that functionality of `tar`

## Related issues

https://github.com/CONP-PCNO/conp-portal/issues/476

**Comment by cmadjar** [comment]
It does not look like DataLad supports the creation of multi-part archive with `datalad export-archive` based on the documentation in http://docs.datalad.org/en/latest/generated/man/datalad-export-archive.html and a quick review of the DataLad code. @yarikoptic, am I misinterpreting?

If not supported, we could always run `split` on the created large archive to chunk it into smaller multiple archives: `split -b 1000m file.tar.gz "file.tar.gz.part"`. Will create files of 1000MB labelled `file.tar.gz.partaa`, `file.tar.gz.partab`, `file.tar.gz.partac` and so on.

**Comment by yarikoptic** [comment]
unfortunately "not yet", but "thought about": please see https://github.com/datalad/datalad/issues/2038 and https://github.com/datalad/datalad/issues/4155 .

I think, if "a tarball per sub-directory" (https://github.com/datalad/datalad/issues/2038) would fit your case -- IMHO it would be a much better solution that splitting [*].  And I think it should be relatively easy to code up.  The https://github.com/datalad/datalad/issues/4155 is a little more ambitious and (hopefully) not required for your use-case.

[*] in particular with `split` which then would be "archiver agnostic" and thus forbidding to index files as available from the archive. I had similar problems with some datasets on CRCNS... not fun.

**Comment by yarikoptic** [comment]
> supports that functionality of `tar`

I guess you mean

```
       -M, --multi-volume
              Create/list/extract multi-volume archive.
```
?  I do not think we support that ATM... would require some research and likely to be more difficult to implement than aforementioned "per directory" splitting.

**Comment by yarikoptic** [comment]
may be @mih or @bpoldrack have more ideas based on the experience with RIA/ORA archives.

**Comment by bpoldrack** [comment]
> may be @mih or @bpoldrack have more ideas based on the experience with RIA/ORA archives.

RIA/ORA archives are a different case, since we put annex' objects tree in an archive, not the worktree. (Also kinda solves the backreferencing issue).

**Comment by cmadjar** [comment]
In the end, we are able to stream the download of big archives so this won't be needed.
