### ISSUE TITLE
Dats model file validator 

### ISSUE THREAD

**Issue by gi114** [CONP-PCNO/conp-dataset#66]
## Purpose
Validate Dats model based files in terms of structure, use of standard keys and required, recommanded and optional fields 

## Context
Automatic test on dataset dats.json files

## Possible Implementation
Currently a perl and a python scripts were attempted to accomplish this functionality:
- Perl: https://github.com/conpdatasets/1000GenomesProject/blob/44a7ee921ec5e1ced3991fab443d50f5af94d2bb/scripts/1000genomes_validate_json.pl
- Python library: dats-tools

Both are currently being tested but seem to use only a JSON validator only. DATS model features should also be validated

**Comment by emmetaobrien** [comment]
That perl script validates a JSON file against a user-specified schema file, and is intended for use with schemas from https://github.com/biocaddie/DATS - so if you give it https://github.com/biocaddie/DATS/dataset_schema.json as input, it already is validating DATS model features.

**Comment by gi114** [comment]
HI, thank you for your message. Yes, I did try that and found that the perl
scripts validates only the overall structure, for example brackets, empty
fields, but it does not know anything about the fields keys that are
present in the file to be validated. With that respect, the "description"
key could be anything else, or not be there at all.

What we want is to give a clue of the required, recommended and optional
fields in a DATS model and validate their presence. In case required fields
are missing from the tested file, the validator will give out an error and
will notify the user of the missing fields. Such feature will be added to
the json-ld schema validator

Hope this clarifies,
Giulia

Il giorno lun 29 lug 2019 alle ore 09:18 emmetaobrien <
notifications@github.com> ha scritto:

**Comment by emmetaobrien** [comment]
I have just tested this script against the DATS.json file for 1000 Genomes Data, removing the "title" field, and I get the following result:

```
~/DATS_schemata$  perl ../perlscripts/validate_json.pl ../1000genomes_data/DATS.json dataset_schema.json
/title: Missing property. at ../perlscripts/validate_json.pl line 60.
```
Can you confirm whether you get the same result ?

**Comment by gi114** [comment]
Hi,

I did launch the same command and had errors on the json structure, @type
key but not on other cases. I will test the title as well and will let you
know what I get.

Apologies for replying late, I only work Thursdays and Fridays, so will get
back to you tomorrow on this

Best
Giulia

**Comment by gi114** [comment]
Hi,

I just tested the validator on this file: https://github.com/CONP-PCNO/dats-validator/blob/Dats-key-validator/dats/dataset.json

This dataset.json file should have all fields recommended and required by the DATS (except version). I believe the $schema should also be removed

I tested it by deleting title and I got the following:
```perl validate_json.pl datsError.json json-schemas/dataset_schema.json 
/: Properties not allowed: $schema, indentifier. at validate_json.pl line 62```

Though the identifier is a recommended field in DATS. I removed $schema and identifier and it goes:

```/title: Missing property. /creators/0: oneOf failed: Properties not allowed: $schema. Properties not allowed: $schema, affiliations, firstName, fullName, lastName. /creators/1: oneOf failed: Properties not allowed: $schema. Properties not allowed: $schema, affiliations, firstName, fullName, lastName. /dates: Expected array - got object. /keywords/0: Properties not allowed: $schema, information. /keywords/1: Properties not allowed: $schema, information. /keywords/2: Properties not allowed: $schema, information. /keywords/3: Properties not allowed: $schema, information. /keywords/4: Properties not allowed: $schema, information. /licenses/0: Properties not allowed: $schema, dataUsesConditions. /primaryPublications/0: Properties not allowed: $schema. /storedIn/access: Expected array - got object. /storedIn/identifier: Expected object - got string. /types/0/information: Properties not allowed: $schema. /types/1/information: Properties not allowed: $schema. /types/2/information: Properties not allowed: $schema. /types/3/information: Properties not allowed: $schema. at validate_json.pl line 62.```

Some properties here said "not allowed" should be part of the DATS based file, such as PrimaryPublications. This validation does not seem to be in line with what should be in the DATS file. 

Let me know what you think. I will send you the Excel with recommended and required fields. 

This is a link to the DATS validator under development: https://github.com/CONP-PCNO/dats-validator/tree/Dats-key-validator/dats

**Comment by emmetaobrien** [comment]
Update to confirm the status of the perl DATS.json validator; correct usage of this script is:

```validate_json.pl <metadata_filename> <schema_filename>```

and (for the moment) the script expects to be run in the directory containing <schema_filename> with the relative path to <,metadata_filename> explicitly specified.

The above problems came about due to unclear communication about that usage, and the script itself is functioning correctly.

(Updating the issue here so there is an appropriate record.)
