### ISSUE TITLE
Generate log file for dats jsonld annotator

### ISSUE THREAD

**Issue by surchs** [CONP-PCNO/conp-dataset#668]
## Purpose
Add the option to have the complete, verbose log of the [DATS jsonld annotator](https://github.com/CONP-PCNO/conp-dataset/blob/master/scripts/dats_jsonld_annotator/annotator.py) dumped to a file.

## Context
When running the annotator over many datasets, many logging events with low priority will be created. 
For example, if unexpected values are encountered in the DATS file that are then not annotated to schema.org. 
It could be useful for a user to have access to the complete log in a file

## Possible Implementation (optional)
- add flag to create log file
- have a second logger config that logs to a file
- have the logging level be low (e.g. DEBUG)

## Related issues (optional)
#640

**Comment by cmadjar** [comment]
@surchs is this still on your roadmap for December?

**Comment by surchs** [comment]
@cmadjar: I think I'll discuss this with Adeel who is probably going to be the main consumer of the code and the files it creates. But I think this could make sense to add and it is on my agenda for December.
