### ISSUE TITLE
DATS annotator should log how many terms were not annotated

### ISSUE THREAD

**Issue by surchs** [CONP-PCNO/conp-dataset#669]
## Purpose
The [DATS annotator](https://github.com/CONP-PCNO/conp-dataset/blob/master/scripts/dats_jsonld_annotator/annotator.py) should tell the user at the end of the annotation process how many terms in each annotated DATS file were not annotated.

## Context
We can only map terms to schema.org / JSONLD if they are defined in the DATS schema. 
If a DATS file contains additional terms (where this is allowed), 
we won't know how to map them to schema.org and they will be skipped. 
It could be interesting to know how often this happens for each DATS file, 
and maybe even what the terms are. 

This would in part be addressed by #668, 
because the verbose log file will contain information on terms that were not found in the DATS schema.
But it would be better to have this information be returned separately to the user.

## Possible Implementation (optional)
- create a log file just for the terms that were not annotated
- store not annotated terms in a dictionary (DATS file name as keys, terms in list) and use the dict to report the total number of not annotated terms to the user at the end of the process

## Related issues (optional)
#668

**Comment by cmadjar** [comment]
@surchs is this still on your roadmap for December?

**Comment by surchs** [comment]
@cmadjar. Yes, similar to #668, I'll have a chat with Adeel but this would make sense to add for December.
