### ISSUE TITLE
nhpatlas - verification of content failed when downloading

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#673]
When downloading the nhpatlas dataset, get the following error:
```
$ datalad get well_data_files.xml 
[WARNING] Running get resulted in stderr output: git-annex: get: 1 failed       
 
[ERROR  ] verification of content failed [get(/data-scratch1/test/conp-dataset/projects/nhpatlas/well_data_files.xml)] 
get(error): /data-scratch1/test/conp-dataset/projects/nhpatlas/well_data_files.xml (file) [verification of content failed]
```
@emmetaobrien is that a dataset you are familiar with? Could you take a look? Thanks!

For some reason this is not picked up by the Circle CI tests. Maybe @mathieu have an idea why this is not picked up by the tests.

**Comment by emmetaobrien** [comment]
This issue is corrected by https://github.com/CONP-PCNO/conp-dataset/pull/687.
