### ISSUE TITLE
Improve handling of DATS files generated by the editor on Zenodo

### ISSUE THREAD

**Issue by surchs** [CONP-PCNO/conp-dataset#678]
## Purpose
If a user uses the https://portal.conp.ca/dats-editor to create a `DATS` file for a Zenodo submission, there should be a note that a certain file name is expected for this DATS file to actually be found by the crawler

## Context
Right now, the DATS editor generates a file of the form `DATS_todays_date_string.json`. However, if the user uploads this to Zenodo, the DATS file will be ignored by the crawler since it is looking for `DATS.json`. We have to go back and ask the user to change the name.

## Possible Implementation (optional)
Some ideas
- [ ] put a note on the DATS editor (e.g. last page) that if the plan is to upload to Zenodo, to please make sure the file is called `DATS.json`
- [x] return the DATS file as `DATS.json` from the editor and let the users system handle duplicates
- [ ] extend the crawler to go looking for other DATS files in the Zenodo repo, possibly ingesting the most recent (possibly not a great plan)

**Comment by elisaguma** [comment]
As a user, changing the filename of a file is not sufficient to create a new version. You would need to modify the file for zenodo to accept the change.
