### ISSUE TITLE
conp-dev.loris.ca server ssh port is not open

### ISSUE THREAD

**Issue by gi114** [CONP-PCNO/conp-dataset#68]
## Purpose
Trying to ssh to conp-dev.loris.ca in order to add a new dataset to CONP

## Context
The default port for ssh (port 22) is filtered for some blockage maybe firewall. This is blocking the addition of the dataset. It is required help from someone managing this server access

**Comment by shots47s** [comment]
@gi114, the machine may be behind our firewall, try logging into 'login-host-1.acelab.ca' first and then you should be able to get on, or you can use the McGill VPN.

**Comment by gi114** [comment]
@shots47s, thanks. It is asking me for a password which I do not have. How should I go about it?
