### ISSUE TITLE
Cannot download one file of the openpain placebo_1 dataset

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#699]
While trying to create the archive for the openpain placebo_1 dataset, one of the file cannot be downloaded for some reason. It says the remote is unavailable.

```
PL101/visit4/funct/PL101_visit4_resting1.nii.gz
```

**Comment by emmetaobrien** [comment]
This file has downloaded straightforwardly and correctly for me since.

**Comment by emmetaobrien** [comment]
Still not reproducible, so I thin it can go down as a transient issue.

**Comment by cmadjar** [comment]
@emmetaobrien after reinstalling from scratch I was finally able to download all the files including the one mentioned above. No idea why I could not download it before... The tar of the dataset is now being created. Thank you for having checked!!
