### ISSUE TITLE
Some files do not get added to Annex when Datalad download URL

### ISSUE THREAD

**Issue by gi114** [CONP-PCNO/conp-dataset#70]
## Current vs Expected Behavior
While adding a new dataset to datalad by giving the download URL for each of the data sub repositories, I see that _some_ .tif .json and .mat (maybe others I have not tried) files do not get added to annex as expected. Others instead get added correctly

Sample errors logs:
[ERROR  ] unknown archive format for file `/data/conp/FRDR-multimodal-dataset/.git/annex/objects/j3/J4/MD5E-s409206536--5fd0cdf151504e0b1fb048495a9feb77.tif/MD5E-s409206536--5fd0cdf1$

[ERROR  ] unknown archive format for file `/data/conp/FRDR-multimodal-dataset/.git/annex/objects/01/Q8/MD5E-s1197559863--22d1dfe08219572fbb67cfa9e520709d.mat/MD5E-s1197559863--22d1df$

[ERROR  ] unknown archive format for file `/data/conp/FRDR-multimodal-dataset/.git/annex/objects/pv/PX/MD5E-s1105606786--55f6b957c16a798f1e9b4bee8235face.mat/MD5E-s1105606786--55f6b9$

[ERROR  ] unknown archive format for file `/data/conp/FRDR-multimodal-dataset/.git/annex/objects/5w/wK/MD5E-s983638399--3b2da1cd255cef8d4409bbf252f07d56.mat/MD5E-s983638399--3b2da1cd$

## Current workaround I used to force files to annex
$ git annex unannex file
$ git add file
$ git commit -m "message"

**Comment by jbpoline** [comment]
Hi Giulia - 
could you put the code that led to the error in the issue so that we can reproduce it ? 
quick question: do you think this is a git annex issue or a datalad one ?

**Comment by gi114** [comment]
Here I have an example with a .mat file:

```$ datalad download-url --archive url_to_mask.mat
```

[INFO   ] Downloading 'https://2a9f4.8443.dn.glob.us/5/published/publication_170/submitted_data/2015_5_6_striatum/mask/2015-5-6_mask.mat' into '/data/conp/multimodal-FRDR-dataset' 
**download_url(ok)**: /data/conp/multimodal-FRDR-dataset/2015-5-6_mask.mat (file)                                                         
**add(ok)**: 2015-5-6_mask.mat (file)
**save(ok)**: /data/conp/multimodal-FRDR-dataset (dataset)

[INFO   ] Adding content of the archive /data/conp/multimodal-FRDR-dataset/2015-5-6_mask.mat into annex <AnnexRepo path=/data/conp/multimodal-FRDR-dataset (<class 'datalad.support.annexrepo.AnnexRepo'>)> 

[ERROR  ] unknown archive format for file `/data/conp/multimodal-FRDR-dataset/.git/annex/objects/34/x8/MD5E-s575--b5333e072291f215595c9c39cd2524e5.mat/MD5E-s575--b5333e072291f215595c9c39cd2524e5.mat' [__init__.py:get_archive_format:293] (PatoolError) 

It looks like how Annex manages files under the cover but I cannot exclude that it is how datalad makes use of Annex. I will investigate on this one

**Comment by gi114** [comment]
Hi,

From further investigation it looks like an Annex problem. The datalad command above has a flag ```--archive``` that allows passing downloaded files to ```datalad add-archive-content -delete```

There are different types of archives in git annex which support different files. Archives are required for storing repository data

**Comment by jbpoline** [comment]
Hi @gi114  - what about not using the --archive flage (as this seems to add content, and we are trying to avoid adding content :)

**Comment by gi114** [comment]
Hi @jbpoline, yes I thought about it. Will give it a try

**Comment by jbpoline** [comment]
hey - was that resolved by not putting the `--archive` ? Michael says archive is only if you want to extract stuff from an archive (not the case for a mat file :)
