### ISSUE TITLE
Adding workflow description of "Updating a Dataset" in README

### ISSUE THREAD

**Issue by gi114** [CONP-PCNO/conp-dataset#73]
## Purpose
We would like to give a clear understanding and instructions on how to update a given dataset which stands as a git submodule in the CONP-dataset repository

## Possible Implementation 
A drawing can be very effective to demonstrate the relationship between the dataset origin/master repository and the CONP-dataset repository that has the dataset as a submodule, or in other words it holds a reference to the original dataset location which needs to reflect updates when the dataset is updated at the origin. 

The drawing I am showing here summarizes the main steps to be taken using the SIMON-dataset as an example. Additional code will be given to instruct on how to update a git submodule 

Let me know your feedback on this!

![conpdataset-CONP interaction submodules update](https://user-images.githubusercontent.com/17640807/63621403-d4bc9700-c5c1-11e9-8304-787b64e30187.png)

**Comment by glatard** [comment]
Hi @gi114, that would be very useful indeed!
A few questions and comments:
- Are you talking only about "updating" a dataset, or is dataset creation covered too?
- In steps 1 and 2, I don't think branching and PR'ing is necessary, although it might be useful when working on multiple changes concurrently. I would remove that, to get the simplest possible workflow.
- I would use "dataset-name" instead of "SIMON-dataset"
- Step 2: I don't understand "CONP-dataset" needs to reflect such changes.
- Eventually this diagram should be added to the contribution guide in CONTRIBUTING.md

**Comment by gi114** [comment]
Hi @glatard, 
Thank you for your message: 
- So I am talking about updating a dataset only here
- In steps 1 and 2 I think the user will have to make a branch/raise PR because changes need to be approved from the team if, let's say, we want to modify the dats.json file. Do you mean to just remove it from the steps description here?
- Agree, will chance SIMON-dataset to generic dataset-name
- So when a change is approved and a dataset is updated in the master repository (here conpdataset - this is the original place where the dataset lives), it is not automatic that those changes get reflected in the repository that ONLY points at such dataset location in the master (the repository pointing is CONP-dataset, which thus only holds a reference to the original dataset location, or we can also say that has the dataset as a git submodule). We need to actively perform some commands to refresh/update the pointer as see the latest dataset updates on our side (CONP-dataset). When that is done, the CI tests will also see those updates. This is shown in Step 3.
Here I have the commands necessary to perform this update. I will add them to the full explanation as well. 
[UpdatingDatasetsWorkflow.txt](https://github.com/CONP-PCNO/conp-dataset/files/3556224/UpdatingDatasetsWorkflow.txt)

- Agree with adding this to CONTRIBUTING.md

**Comment by gi114** [comment]
Hi,

Here I changed the SIMON-dataset to general <dataset-name>

Let me know your thoughts
![conpdataset-CONP interaction submodules update](https://user-images.githubusercontent.com/17640807/64362085-dc296a80-cfdb-11e9-8a4a-bcb7c506b831.png)
