### ISSUE TITLE
Merge folders "investigators" and "projects" into a new folder called "datasets"

### ISSUE THREAD

**Issue by joeyzhou98** [CONP-PCNO/conp-dataset#74]
## Purpose
Merge folders "investigators" and "projects" into a new folder called "datasets" in order to have better structural organization

## Context
I am currently writing a Zenodo crawler to allow people to more easily upload datasets via a more automatized way where they can just upload their dataset to Zenodo with a "canadian-open-neuroscience-portal" tag/keyword and my script will retrieve those datasets and open pull requests to this repository. Having a single folder for datasets would simplify both organization and easy of access for everyone

## Possible Implementation (optional)
Simply move all the datasets in "investigators" and "projects" into a new one called "datasets"

**Comment by jbpoline** [comment]
I am in favor of this - but with no hierarchy, if the number of datasets gets large (a good problem to have) browsing in the portal may become cumbersome. This would be mitigated by a search system on tags.

**Comment by joeyzhou98** [comment]
@glatard yes, I will take care of this next
