### ISSUE TITLE
Datalad publish ERROR: stderr: 'error: RPC failed; curl 55 Failed sending data to the peer | fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by gi114** [CONP-PCNO/conp-dataset#76]
#### What is the problem and steps
This issue here is in the context of creating and populating a new dataset, creating a github sibling and finally publishing/pushing to github

So I create a sibling after populating my dataset. Everything is tracked so my ```datalad status``` has no output. Here it is my sibling information:

```
$ datalad siblings query -d . --url FRDR-multimodal-dataset
.: here(+) [git]
.: github(-) [https://gi114@github.com/conpdatasets/FRDR-multimodal-dataset.git (git)]
```
Therefore I want to push my changes to github
```
$ datalad publish -r --to github

[INFO   ] Publishing <Dataset path=/data/conp/FRDR-multimodal-dataset> to github 
[ERROR  ] Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(1)                                                                                                                                   
|   cmdline: /usr/lib/git-annex.linux/git -c receive.autogc=0 -c gc.auto=0 push --porcelain --progress github FRDR-dataset git-annex
|   stderr: 'error: RPC failed; curl 55 Failed sending data to the peer
| fatal: the remote end hung up unexpectedly
```

I wonder what it is going on as I cannot fix the problem. I tried to increase the http.postBuffer to 35Gb, which is just above the size of my dataset, but it did not work.

Datalad version: ```datalad 0.12.0rc2```
OS: Linux, Ubuntu 18.04

#### Useful links
I added this issue in the datalad repository as well, so we may follow updates there [here](https://github.com/datalad/datalad/issues/3632)

Thanks you for your help,
Giulia

**Comment by jbpoline** [comment]
@gi114  : 

siblings seem fine

where did you try to run that command from ? can I / someone go to that place and look at the dataset you are trying to publish?  what branch are you on when you are trying to push ?

if there is no subdatasets then `-r` is not needed

**Comment by gi114** [comment]
Hi @jbpoline,

I am currently working in the lorisadmin@conp-dev.loris.ca machine, port 22014. Specifically in the /data/conp folder I created a datalad dataset called FRDR-multimodal-dataset

I did a lot of search but I still have issues understanding what is causing the problem. The machine is currently down for a power outage but should be back soon

**Comment by PapillonMcGill** [comment]
Hello Giulia,

Can you delete the last comment you made at view it on GitHub<https://github.com/CONP-PCNO/conp-dataset/issues/76?email_source=notifications&email_token=AIFY3XJJXQVUJTR2KPHDJG3QIEQ6DA5CNFSM4ISQ24X2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD57SKTY#issuecomment-528426319> Short of giving the password, all connections details are now public. This can cause a security issue.

Please be cautious what you post on GitHub, regarding the server.

You can reply privatly using email for those case.

thanks


Mélanie


________________________________

**Comment by glatard** [comment]
Hi @gi114, not sure if this is still relevant, feel free to reopen if it is.

**Comment by gi114** [comment]
Hi @glatard ,

Thanks for asking, this is no more relevant
