### ISSUE TITLE
Automatic dataset upload and update via zenodo crawler

### ISSUE THREAD

**Issue by joeyzhou98** [CONP-PCNO/conp-dataset#79]
## Purpose
The current system for uploading datasets to conp-dataset is complicated and hard to use for non programmers. Zenodo is easier to use and is flexible enough for people to upload their dataset. Having dataset owners upload to Zenodo then we can retrieve their dataset into this repository via a crawler and pull request.

## Context
This would facilitate dataset uploads and updates as dataset owners will only have to interact with Zenodo, plus there might be other side benefits such as more reliable structure and less prone to human errors if it is via a well coded crawler.

## Possible Implementation (optional)
1. Make sure you have an up to date repository by pulling
2. Retrieve all current conp-dataset information stored in dats.json files (concept_doi and version_doi)
3. Retrieve all metadata for all zenodo datasets containing the keyword `canadian-open-neuroscience-platform`
4. Looping through the retrieved zenodo datasets metadata:
    1. If zenodo dataset is existing in a conp-dataset by comparing concept_doi:
        1. If the conp-dataset version is not current by comparing the zenodo dataset latest_version_doi with the conp-dataset version_doi:
            1. Update conp-dataset
    2. If the zenodo dataset doesn't exist in conp-dataset by seeing that the zenodo concept_doi is not in the concept_dois retrieved from conp-datasets
        1. Download zenodo dataset into a new dataset/directory
5. Create pull requests with changes

**Comment by dlq** [comment]
If it’s uploaded first to Zenodo, does it need to be in `conp-dataset`?

**Comment by glatard** [comment]
Yes, the point is to facilitate upload to conp-dataset through Zenodo.

**Comment by glatard** [comment]
This has been operational for a few months now.
