### ISSUE TITLE
[Datasets] Different Repos for public and private metadata?

### ISSUE THREAD

**Issue by stronics** [CONP-PCNO/conp-dataset#8]
There should be further discussions on whether we want to have a `conp-dataset-public` for public metadata and a `conp-dataset-private` for private metadata. 

Another possibility is to agree that **all** metadata should be public, but we remove files in the annex in the public `conp-dataset` and keep it as a separate private repo on Github. Only whitelisted users will be able to access these private annex files and download the data.

**Comment by glatard** [comment]
The best would be to handle this through GitHub permissions on sub-datasets.
