### ISSUE TITLE
Standardizing the name of the dats.json file

### ISSUE THREAD

**Issue by shots47s** [CONP-PCNO/conp-dataset#85]
## Purpose
There seems to be ambiguity in how the dats files are named in each directory.

## Context
In the mulitcentered-phantom, the dats file is named `multicentered-phantom-dats.json`

## Possible Implementation (optional)
We should declare that all dats files have the same name in the top level directory of the submodule, so that they are easily findable.  I would recommend `dats.json` so that we do not run into case sensitivity.

## Related issues (optional)
https://github.com/CONP-PCNO/conp-portal/issues/76

**Comment by jbpoline** [comment]
The recommendation was DATS.json (IIRC) but lower case sounds good to me

**Comment by shots47s** [comment]
Hmm, I am just worried about case insensitive, as long as it is definitely one or the other:

On mac and windows DaTS.json == Dats.json == dats.json == DATS.json

**Comment by jbpoline** [comment]
Not sure  I get what you mean : do you mean the code should handle the file name as case insensitive ? sounds reasonalble - or do you want to recommend lower case to avoid the pb (which I would favor)

**Comment by shots47s** [comment]
yes :)

**Comment by jbpoline** [comment]
remember that in predicate logic A OR B is true iif A is true, or if B is true :)

**Comment by shots47s** [comment]
Or in the immortal words of the President of the Federation of Planets in Star Trek VI, "Just because we can do a thing, doesn't mean we should do a thing".
