### ISSUE TITLE
Separate integration tests from monitoring

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-dataset#89]
## Purpose

Tests currently test all the datasets systematically with every PR. This doesn't scale and will create timeouts when the number of datasets grows. 

Instead, we should restrict the tests to check only the latest additions to the conp-dataset repo, including new sub-modules and updates in current sub-modules.

## Context

* It would reduce the testing time
* It would allow to test more than 4 random files when a new dataset is added

## Possible Implementation

* After testing a dataset, make Travis commit the following info to a "tested.json" file at the root of the repo:
   - name of the dataset (sub-module), latest tested commit
* When the tests start, skip the sub-modules for which the latest commit has already been tested.
* Separately from CI, setup a monitoring server (Nagios?) that would test all the datasets 
periodically (create a separate issue when the present one is implemented).

This is coming from a discussion with @mathdugre. @joeyzhou98, this is for you when you're done with your current task!

**Comment by shots47s** [comment]
This is an excellent point, if we get 100s of datasets, this will fail. +1

**Comment by jbpoline** [comment]
Indeed +1
we should also have a mechanism to review all datasets periodically to see which ones cannot be downloaded and tag these

**Comment by shots47s** [comment]
Correct, that is the point above about Nagios.  The purpose of our CI is test new Datasets for integration, and maybe some spot check, but we also don't want someone who is bringing in a new dataset to fail because of other datasets having intermittent issues, this is the job of something like Nagios, that we could run very regularly.  Thank or bringing it up @glatard, @joeyzhou98 , and @mathdugre, this part should go the infrastructure.

**Comment by glatard** [comment]
Here is a better implementation plan, following today's discussion with @satra, @shots47s and @jbpoline:
1. Make a shallow clone of the master branch
2. Make a git diff with the incoming PR
3. From the diff, identify the datasets that are touched by the PR
4. For each touched dataset, run the tests
@joeyzhou98, let us know how that sounds!

**Comment by glatard** [comment]
This is now supported as part of the test suite.
