### ISSUE TITLE
[Suggestion] Create a cloud migration protocol/connect CONP to the cloud.

### ISSUE THREAD

**Issue by kchatpar** [CONP-PCNO/conp-dataset#9]
One trend that is quite prevalent in the scientific industry is storing data on hard drives and not servers. CONP assumes that the lab is storing there data on a server. Providing a protocol on how to migrate data onto AWS(any cloud server) and for CONP to be able to access laboratory data stored in the cloud is quite  important.

Solution: provide laboratory's with a VM through a cloud re-seller with datalad and the infrastructure to connect to COMP. This can be used for lab data storage and to connect to CONP.

**Comment by jbpoline** [comment]
Yes, we had some discussions around this kind of idea, thanks for posting. To be discussed further afer the Toronto meeting.

**Comment by glatard** [comment]
I feel like the Zenodo and OSF integration partially answer that issue. One useful thing though could be to make sure that a ready-to-go container exists that would contain all the required clients to access CONP datasets, i.e., a working combination of DataLad and git-annex. This is for sure available in our tests, but I'm not sure if it's well documented and accessible to users. @mathdugre, would you like to check this and perhaps update the documentation accordingly with @emmetaobrien or @cmadjar?

**Comment by mathdugre** [comment]
@glatard, I will update the documentation to include the CircleCI container.

**Comment by cmadjar** [comment]
@mathdugre @glatard should this be closed?
