### ISSUE TITLE
Error trying to get the Prevent-AD dataset

### ISSUE THREAD

**Issue by MatthieuJoulot** [CONP-PCNO/conp-dataset#921]
Hi,
I am currently trying to get the Prevent-AD dataset following both the documentation on the [conp-pcno](https://portal.conp.ca/dataset?id=projects/preventad-open-bids) and on your [git page](https://github.com/CONP-PCNO/conp-dataset/). I can't manage to get past an error.

## Details
1. As suggested I installed `datalad` and `git-annex`
2. I then used the following command line; `datalad install https://github.com/CONP-PCNO/conp-dataset.git`which brings the following output: 
![Capture d’écran 2024-08-21 à 15 45 56](https://github.com/user-attachments/assets/0a90136f-ee40-4512-88ec-a99b8a7f6927)
3. I then used the following commands `cd conp-dataset` and `datalad install projects/preventad-opend-bids` for which I have the following error:
![Capture d’écran 2024-08-21 à 15 49 24](https://github.com/user-attachments/assets/88fe68bf-29d7-4a39-923d-cbd4bbfa64ea)

## Environment
I am on Ubuntu 22.04

Could help me with this please ?
Have a good day,

**Comment by emmetaobrien** [comment]
Can you confirm which versions of `datalad` and `git-annex` you are using?

**Comment by MatthieuJoulot** [comment]
Ha yes of course sorry.
I am using version `1.1.3` of datalad and version `10.20230626-g8594d49` of git-annex (which was installed though datalad)

**Comment by emmetaobrien** [comment]
I have not been straightforwardly able to duplicate your issue as of this morning, and I am not sure the datalad version number you provide makes sense, can you doublecheck that with `datalad --version`? The standard datalad version for Ubuntu 22.04 should be 0.15.5-1 according to https://launchpad.net/ubuntu/jammy/+package/datalad.  Also there's a typo in the dataset name you list in point 3 of your description above, can you send a screenshot with the install command included?

**Comment by emmetaobrien** [comment]
I have now been able to recreate the error, and we are working on identifying and correcting it.  Will update when I have more specifics.

**Comment by MatthieuJoulot** [comment]
Alright ! thank you so much !

**Comment by emmetaobrien** [comment]
This issue is now showing as resolved on our end, can you try again and confirm whether the `download install preventad-bids-open` command now works for you?
